CSV.tables.sound_resource = {
	[1] = {
		element_index = '场景音乐',
		element_name = '安全区音乐1',
		sound_id = 1,
		sound_path = 'sound/bg_sound/sanguo_city1.mp3',
		sound_type = 0,
	},
	[2] = {
		element_index = '场景音乐',
		element_name = '安全区音乐2',
		sound_id = 2,
		sound_path = 'sound/bg_sound/sanguo_city2.mp3',
		sound_type = 0,
	},
	[3] = {
		element_index = '场景音乐',
		element_name = '战斗音乐1',
		sound_id = 3,
		sound_path = 'sound/bg_sound/sanguo_fight1.mp3',
		sound_type = 0,
	},
	[4] = {
		element_index = '场景音乐',
		element_name = '战斗音乐2',
		sound_id = 4,
		sound_path = 'sound/bg_sound/sanguo_fight2.mp3',
		sound_type = 0,
	},
	[5] = {
		element_index = '场景音乐',
		element_name = '战斗音乐3',
		sound_id = 5,
		sound_path = 'sound/bg_sound/sanguo_fight3.mp3',
		sound_type = 0,
	},
	[6] = {
		element_index = '技能音效',
		element_name = '长枪基本挥动1',
		sound_id = 6,
		sound_path = 'sound/effect_sound/sound_zy_jiben1.mp3',
		sound_type = 1,
	},
	[7] = {
		element_index = '技能音效',
		element_name = '长枪基本挥动2',
		sound_id = 7,
		sound_path = 'sound/effect_sound/sound_zy_jiben2.mp3',
		sound_type = 1,
	},
	[8] = {
		element_index = '技能音效',
		element_name = '长枪基本挥动3',
		sound_id = 8,
		sound_path = 'sound/effect_sound/sound_zy_jiben3.mp3',
		sound_type = 1,
	},
	[9] = {
		element_index = '技能音效',
		element_name = '长枪转圈',
		sound_id = 9,
		sound_path = 'sound/effect_sound/sound_zy_zhuanquan.mp3',
		sound_type = 1,
	},
	[10] = {
		element_index = '技能音效',
		element_name = '长枪抽地',
		sound_id = 10,
		sound_path = 'sound/effect_sound/sound_zy_choudi.mp3',
		sound_type = 1,
	},
	[11] = {
		element_index = '技能音效',
		element_name = '赵云瞬移',
		sound_id = 11,
		sound_path = 'sound/effect_sound/sound_zy_shunyi.mp3',
		sound_type = 1,
	},
	[12] = {
		element_index = '技能音效',
		element_name = '龙盘旋特效',
		sound_id = 12,
		sound_path = 'sound/effect_sound/sound_zy_longpanxuan.mp3',
		sound_type = 1,
	},
	[13] = {
		element_index = '技能音效',
		element_name = '龙爆炸特效',
		sound_id = 13,
		sound_path = 'sound/effect_sound/sound_zy_longbaozha.mp3',
		sound_type = 1,
	},
	[14] = {
		element_index = '技能音效',
		element_name = '半月斩特效',
		sound_id = 14,
		sound_path = 'sound/effect_sound/sound_zy_banyuezhan.mp3',
		sound_type = 1,
	},
	[15] = {
		element_index = '技能音效',
		element_name = '羽扇基本挥动1',
		sound_id = 15,
		sound_path = 'sound/effect_sound/sound_zg_jiben1.mp3',
		sound_type = 1,
	},
	[16] = {
		element_index = '技能音效',
		element_name = '羽扇基本挥动2',
		sound_id = 16,
		sound_path = 'sound/effect_sound/sound_zg_jiben2.mp3',
		sound_type = 1,
	},
	[17] = {
		element_index = '技能音效',
		element_name = '羽扇基本挥动3',
		sound_id = 17,
		sound_path = 'sound/effect_sound/sound_zg_jiben3.mp3',
		sound_type = 1,
	},
	[18] = {
		element_index = '技能音效',
		element_name = '诸葛瞬移',
		sound_id = 18,
		sound_path = 'sound/effect_sound/sound_zg_shunyi.mp3',
		sound_type = 1,
	},
	[19] = {
		element_index = '技能音效',
		element_name = '急风冲刺特效',
		sound_id = 19,
		sound_path = 'sound/effect_sound/sound_zg_jifengchongci.mp3',
		sound_type = 1,
	},
	[20] = {
		element_index = '技能音效',
		element_name = '横龙卷风特效',
		sound_id = 20,
		sound_path = 'sound/effect_sound/sound_zg_henglongjuan.mp3',
		sound_type = 1,
	},
	[21] = {
		element_index = '技能音效',
		element_name = '冰针飞行特效',
		sound_id = 21,
		sound_path = 'sound/effect_sound/sound_zg_bingzhen.mp3',
		sound_type = 1,
	},
	[22] = {
		element_index = '技能音效',
		element_name = '大冰锥飞行落地特效',
		sound_id = 22,
		sound_path = 'sound/effect_sound/sound_zg_bingzhui.mp3',
		sound_type = 1,
	},
	[23] = {
		element_index = '技能音效',
		element_name = '雷电特效',
		sound_id = 23,
		sound_path = 'sound/effect_sound/sound_zg_leidian.mp3',
		sound_type = 1,
	},
	[24] = {
		element_index = '技能音效',
		element_name = '八卦雷球特效',
		sound_id = 24,
		sound_path = 'sound/effect_sound/sound_zg_leiqiu.mp3',
		sound_type = 1,
	},
	[25] = {
		element_index = '技能音效',
		element_name = '小火鸟特效',
		sound_id = 25,
		sound_path = 'sound/effect_sound/sound_zg_xiaohuoniao.mp3',
		sound_type = 1,
	},
	[26] = {
		element_index = '技能音效',
		element_name = '大火鸟飞行特效',
		sound_id = 26,
		sound_path = 'sound/effect_sound/sound_zg_dahuoniao.mp3',
		sound_type = 1,
	},
	[27] = {
		element_index = '技能音效',
		element_name = '火球飞行特效',
		sound_id = 27,
		sound_path = 'sound/effect_sound/sound_zg_huoqiu.mp3',
		sound_type = 1,
	},
	[28] = {
		element_index = '技能音效',
		element_name = '火球爆炸特效',
		sound_id = 28,
		sound_path = 'sound/effect_sound/sound_zg_huoqiubaozha.mp3',
		sound_type = 1,
	},
	[29] = {
		element_index = '技能音效',
		element_name = '双剑基本攻击1',
		sound_id = 29,
		sound_path = 'sound/effect_sound/sound_dc_jiben1.mp3',
		sound_type = 1,
	},
	[30] = {
		element_index = '技能音效',
		element_name = '双剑基本攻击2',
		sound_id = 30,
		sound_path = 'sound/effect_sound/sound_dc_jiben2.mp3',
		sound_type = 1,
	},
	[31] = {
		element_index = '技能音效',
		element_name = '双剑基本攻击3',
		sound_id = 31,
		sound_path = 'sound/effect_sound/sound_dc_jiben3.mp3',
		sound_type = 1,
	},
	[32] = {
		element_index = '技能音效',
		element_name = '交叉刀光特效',
		sound_id = 32,
		sound_path = 'sound/effect_sound/sound_dc_jiaocha.mp3',
		sound_type = 1,
	},
	[33] = {
		element_index = '技能音效',
		element_name = '坠地大交叉刀光特效',
		sound_id = 33,
		sound_path = 'sound/effect_sound/sound_dc_dajiaocha.mp3',
		sound_type = 1,
	},
	[34] = {
		element_index = '技能音效',
		element_name = '两次穿梭特效',
		sound_id = 34,
		sound_path = 'sound/effect_sound/sound_dc_chuansuo.mp3',
		sound_type = 1,
	},
	[35] = {
		element_index = '技能音效',
		element_name = '连续穿梭特效',
		sound_id = 35,
		sound_path = 'sound/effect_sound/sound_dc_lianxuchuansuo.mp3',
		sound_type = 1,
	},
	[36] = {
		element_index = '技能音效',
		element_name = '貂蝉瞬移特效',
		sound_id = 36,
		sound_path = 'sound/effect_sound/sound_dc_shunyi.mp3',
		sound_type = 1,
	},
	[37] = {
		element_index = '技能音效',
		element_name = '飞刀飞行特效',
		sound_id = 37,
		sound_path = 'sound/effect_sound/sound_dc_feidao.mp3',
		sound_type = 1,
	},
	[38] = {
		element_index = '技能音效',
		element_name = '花瓣飞行特效',
		sound_id = 38,
		sound_path = 'sound/effect_sound/sound_dc_huaban.mp3',
		sound_type = 1,
	},
	[39] = {
		element_index = '技能音效',
		element_name = '花瓣连续爆炸特效',
		sound_id = 39,
		sound_path = 'sound/effect_sound/sound_dc_huabanbaozha.mp3',
		sound_type = 1,
	},
	[40] = {
		element_index = '技能音效',
		element_name = '乱舞刀光特效',
		sound_id = 40,
		sound_path = 'sound/effect_sound/sound_dc_luanwu.mp3',
		sound_type = 1,
	},
	[41] = {
		element_index = '技能音效',
		element_name = '万剑决特效',
		sound_id = 41,
		sound_path = 'sound/effect_sound/sound_dc_wanjianjue.mp3',
		sound_type = 1,
	},
	[42] = {
		element_index = '人物配音',
		element_name = '大将军-赵云',
		sound_id = 42,
		sound_path = 'sound/npc_sound/npc_dajiangjun1_1.mp3',
		sound_type = 1,
	},
	[43] = {
		element_index = '人物配音',
		element_name = '大将军-赵云',
		sound_id = 43,
		sound_path = 'sound/npc_sound/npc_dajiangjun1_2.mp3',
		sound_type = 1,
	},
	[44] = {
		element_index = '人物配音',
		element_name = '大将军-貂蝉',
		sound_id = 44,
		sound_path = 'sound/npc_sound/npc_dajiangjun2_1.mp3',
		sound_type = 1,
	},
	[45] = {
		element_index = '人物配音',
		element_name = '大将军-貂蝉',
		sound_id = 45,
		sound_path = 'sound/npc_sound/npc_dajiangjun2_2.mp3',
		sound_type = 1,
	},
	[46] = {
		element_index = '人物配音',
		element_name = '大将军-诸葛',
		sound_id = 46,
		sound_path = 'sound/npc_sound/npc_dajiangjun3_1.mp3',
		sound_type = 1,
	},
	[47] = {
		element_index = '人物配音',
		element_name = '大将军-诸葛',
		sound_id = 47,
		sound_path = 'sound/npc_sound/npc_dajiangjun3_2.mp3',
		sound_type = 1,
	},
	[48] = {
		element_index = '人物配音',
		element_name = '督邮',
		sound_id = 48,
		sound_path = 'sound/npc_sound/npc_duyou_1.mp3',
		sound_type = 1,
	},
	[49] = {
		element_index = '人物配音',
		element_name = '李典',
		sound_id = 49,
		sound_path = 'sound/npc_sound/npc_lidian_1.mp3',
		sound_type = 1,
	},
	[50] = {
		element_index = '人物配音',
		element_name = '李典',
		sound_id = 50,
		sound_path = 'sound/npc_sound/npc_lidian_2.mp3',
		sound_type = 1,
	},
	[51] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 51,
		sound_path = 'sound/npc_sound/npc_liubei_1.mp3',
		sound_type = 1,
	},
	[52] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 52,
		sound_path = 'sound/npc_sound/npc_liubei_2.mp3',
		sound_type = 1,
	},
	[53] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 53,
		sound_path = 'sound/npc_sound/npc_liubei_3.mp3',
		sound_type = 1,
	},
	[54] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 54,
		sound_path = 'sound/npc_sound/npc_liubei_4.mp3',
		sound_type = 1,
	},
	[55] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 55,
		sound_path = 'sound/npc_sound/npc_liubei_5.mp3',
		sound_type = 1,
	},
	[56] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 56,
		sound_path = 'sound/npc_sound/npc_liubei_6.mp3',
		sound_type = 1,
	},
	[57] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 57,
		sound_path = 'sound/npc_sound/npc_liubei_7.mp3',
		sound_type = 1,
	},
	[58] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 58,
		sound_path = 'sound/npc_sound/npc_liubei_8.mp3',
		sound_type = 1,
	},
	[59] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 59,
		sound_path = 'sound/npc_sound/npc_liubei_9.mp3',
		sound_type = 1,
	},
	[60] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 60,
		sound_path = 'sound/npc_sound/npc_liubei_10.mp3',
		sound_type = 1,
	},
	[61] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 61,
		sound_path = 'sound/npc_sound/npc_liubei_11.mp3',
		sound_type = 1,
	},
	[62] = {
		element_index = '人物配音',
		element_name = '士兵1',
		sound_id = 62,
		sound_path = 'sound/npc_sound/npc_shibing1_1.mp3',
		sound_type = 1,
	},
	[63] = {
		element_index = '人物配音',
		element_name = '士兵1',
		sound_id = 63,
		sound_path = 'sound/npc_sound/npc_shibing1_2.mp3',
		sound_type = 1,
	},
	[64] = {
		element_index = '人物配音',
		element_name = '士兵1',
		sound_id = 64,
		sound_path = 'sound/npc_sound/npc_shibing1_3.mp3',
		sound_type = 1,
	},
	[65] = {
		element_index = '人物配音',
		element_name = '士兵1',
		sound_id = 65,
		sound_path = 'sound/npc_sound/npc_shibing1_4.mp3',
		sound_type = 1,
	},
	[66] = {
		element_index = '人物配音',
		element_name = '士兵1',
		sound_id = 66,
		sound_path = 'sound/npc_sound/npc_shibing1_5.mp3',
		sound_type = 1,
	},
	[67] = {
		element_index = '人物配音',
		element_name = '士兵1',
		sound_id = 67,
		sound_path = 'sound/npc_sound/npc_shibing1_6.mp3',
		sound_type = 1,
	},
	[68] = {
		element_index = '人物配音',
		element_name = '士兵2',
		sound_id = 68,
		sound_path = 'sound/npc_sound/npc_shibing2_1.mp3',
		sound_type = 1,
	},
	[69] = {
		element_index = '人物配音',
		element_name = '士兵2',
		sound_id = 69,
		sound_path = 'sound/npc_sound/npc_shibing2_2.mp3',
		sound_type = 1,
	},
	[70] = {
		element_index = '人物配音',
		element_name = '士兵2',
		sound_id = 70,
		sound_path = 'sound/npc_sound/npc_shibing2_3.mp3',
		sound_type = 1,
	},
	[71] = {
		element_index = '人物配音',
		element_name = '士兵2',
		sound_id = 71,
		sound_path = 'sound/npc_sound/npc_shibing2_4.mp3',
		sound_type = 1,
	},
	[72] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 72,
		sound_path = 'sound/npc_sound/npc_wanjia1_1.mp3',
		sound_type = 1,
	},
	[73] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 73,
		sound_path = 'sound/npc_sound/npc_wanjia1_2.mp3',
		sound_type = 1,
	},
	[74] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 74,
		sound_path = 'sound/npc_sound/npc_wanjia1_3.mp3',
		sound_type = 1,
	},
	[75] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 75,
		sound_path = 'sound/npc_sound/npc_wanjia1_4.mp3',
		sound_type = 1,
	},
	[76] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 76,
		sound_path = 'sound/npc_sound/npc_wanjia1_5.mp3',
		sound_type = 1,
	},
	[77] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 77,
		sound_path = 'sound/npc_sound/npc_wanjia1_6.mp3',
		sound_type = 1,
	},
	[78] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 78,
		sound_path = 'sound/npc_sound/npc_wanjia1_7.mp3',
		sound_type = 1,
	},
	[79] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 79,
		sound_path = 'sound/npc_sound/npc_wanjia1_8.mp3',
		sound_type = 1,
	},
	[80] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 80,
		sound_path = 'sound/npc_sound/npc_wanjia1_9.mp3',
		sound_type = 1,
	},
	[81] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 81,
		sound_path = 'sound/npc_sound/npc_wanjia1_10.mp3',
		sound_type = 1,
	},
	[82] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 82,
		sound_path = 'sound/npc_sound/npc_wanjia1_11.mp3',
		sound_type = 1,
	},
	[83] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 83,
		sound_path = 'sound/npc_sound/npc_wanjia2_1.mp3',
		sound_type = 1,
	},
	[84] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 84,
		sound_path = 'sound/npc_sound/npc_wanjia2_2.mp3',
		sound_type = 1,
	},
	[85] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 85,
		sound_path = 'sound/npc_sound/npc_wanjia2_3.mp3',
		sound_type = 1,
	},
	[86] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 86,
		sound_path = 'sound/npc_sound/npc_wanjia2_4.mp3',
		sound_type = 1,
	},
	[87] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 87,
		sound_path = 'sound/npc_sound/npc_wanjia2_5.mp3',
		sound_type = 1,
	},
	[88] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 88,
		sound_path = 'sound/npc_sound/npc_wanjia2_6.mp3',
		sound_type = 1,
	},
	[89] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 89,
		sound_path = 'sound/npc_sound/npc_wanjia2_7.mp3',
		sound_type = 1,
	},
	[90] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 90,
		sound_path = 'sound/npc_sound/npc_wanjia2_8.mp3',
		sound_type = 1,
	},
	[91] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 91,
		sound_path = 'sound/npc_sound/npc_wanjia2_9.mp3',
		sound_type = 1,
	},
	[92] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 92,
		sound_path = 'sound/npc_sound/npc_wanjia2_10.mp3',
		sound_type = 1,
	},
	[93] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 93,
		sound_path = 'sound/npc_sound/npc_wanjia2_11.mp3',
		sound_type = 1,
	},
	[94] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 94,
		sound_path = 'sound/npc_sound/npc_wanjia3_1.mp3',
		sound_type = 1,
	},
	[95] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 95,
		sound_path = 'sound/npc_sound/npc_wanjia3_2.mp3',
		sound_type = 1,
	},
	[96] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 96,
		sound_path = 'sound/npc_sound/npc_wanjia3_3.mp3',
		sound_type = 1,
	},
	[97] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 97,
		sound_path = 'sound/npc_sound/npc_wanjia3_4.mp3',
		sound_type = 1,
	},
	[98] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 98,
		sound_path = 'sound/npc_sound/npc_wanjia3_5.mp3',
		sound_type = 1,
	},
	[99] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 99,
		sound_path = 'sound/npc_sound/npc_wanjia3_6.mp3',
		sound_type = 1,
	},
	[100] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 100,
		sound_path = 'sound/npc_sound/npc_wanjia3_7.mp3',
		sound_type = 1,
	},
	[101] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 101,
		sound_path = 'sound/npc_sound/npc_wanjia3_8.mp3',
		sound_type = 1,
	},
	[102] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 102,
		sound_path = 'sound/npc_sound/npc_wanjia3_9.mp3',
		sound_type = 1,
	},
	[103] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 103,
		sound_path = 'sound/npc_sound/npc_wanjia3_10.mp3',
		sound_type = 1,
	},
	[104] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 104,
		sound_path = 'sound/npc_sound/npc_wanjia3_11.mp3',
		sound_type = 1,
	},
	[105] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 105,
		sound_path = 'sound/npc_sound/npc_yunji_1.mp3',
		sound_type = 1,
	},
	[106] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 106,
		sound_path = 'sound/npc_sound/npc_yunji_2.mp3',
		sound_type = 1,
	},
	[107] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 107,
		sound_path = 'sound/npc_sound/npc_yunji_3.mp3',
		sound_type = 1,
	},
	[108] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 108,
		sound_path = 'sound/npc_sound/npc_yunji_4.mp3',
		sound_type = 1,
	},
	[109] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 109,
		sound_path = 'sound/npc_sound/npc_yunji_5.mp3',
		sound_type = 1,
	},
	[110] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 110,
		sound_path = 'sound/npc_sound/npc_yunji_6.mp3',
		sound_type = 1,
	},
	[111] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 111,
		sound_path = 'sound/npc_sound/npc_yunji_7.mp3',
		sound_type = 1,
	},
	[112] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 112,
		sound_path = 'sound/npc_sound/npc_yunji_8.mp3',
		sound_type = 1,
	},
	[113] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 113,
		sound_path = 'sound/npc_sound/npc_yunji_9.mp3',
		sound_type = 1,
	},
	[114] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 114,
		sound_path = 'sound/npc_sound/npc_zhugeliang_1.mp3',
		sound_type = 1,
	},
	[115] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 115,
		sound_path = 'sound/npc_sound/npc_zhugeliang_2.mp3',
		sound_type = 1,
	},
	[116] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 116,
		sound_path = 'sound/npc_sound/npc_zhugeliang_3.mp3',
		sound_type = 1,
	},
	[117] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 117,
		sound_path = 'sound/npc_sound/npc_zhugeliang_4.mp3',
		sound_type = 1,
	},
	[118] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 118,
		sound_path = 'sound/npc_sound/npc_zhugeliang_5.mp3',
		sound_type = 1,
	},
	[119] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 119,
		sound_path = 'sound/npc_sound/npc_zhugeliang_6.mp3',
		sound_type = 1,
	},
	[120] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 120,
		sound_path = 'sound/npc_sound/npc_zhugeliang_7.mp3',
		sound_type = 1,
	},
	[121] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 121,
		sound_path = 'sound/npc_sound/npc_zhugeliang_8.mp3',
		sound_type = 1,
	},
	[122] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 122,
		sound_path = 'sound/npc_sound/npc_zhugeliang_9.mp3',
		sound_type = 1,
	},
	[123] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 123,
		sound_path = 'sound/npc_sound/npc_zhugeliang_10.mp3',
		sound_type = 1,
	},
	[124] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 124,
		sound_path = 'sound/npc_sound/npc_zhugeliang_11.mp3',
		sound_type = 1,
	},
	[125] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 125,
		sound_path = 'sound/npc_sound/npc_zhugeliang_12.mp3',
		sound_type = 1,
	},
	[126] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 126,
		sound_path = 'sound/npc_sound/npc_zhugeliang_13.mp3',
		sound_type = 1,
	},
	[127] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 127,
		sound_path = 'sound/npc_sound/npc_zhugeliang_14.mp3',
		sound_type = 1,
	},
	[128] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 128,
		sound_path = 'sound/npc_sound/npc_zhugeliang_15.mp3',
		sound_type = 1,
	},
	[129] = {
		element_index = '人物配音',
		element_name = '诸葛亮',
		sound_id = 129,
		sound_path = 'sound/npc_sound/npc_zhugeliang_16.mp3',
		sound_type = 1,
	},
	[130] = {
		element_index = '人物配音',
		element_name = '刘备',
		sound_id = 130,
		sound_path = 'sound/npc_sound/npc_liubei_12.mp3',
		sound_type = 1,
	},
	[131] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 131,
		sound_path = 'sound/npc_sound/npc_wanjia1_12.mp3',
		sound_type = 1,
	},
	[132] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 132,
		sound_path = 'sound/npc_sound/npc_wanjia1_13.mp3',
		sound_type = 1,
	},
	[133] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 133,
		sound_path = 'sound/npc_sound/npc_wanjia1_14.mp3',
		sound_type = 1,
	},
	[134] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 134,
		sound_path = 'sound/npc_sound/npc_wanjia1_15.mp3',
		sound_type = 1,
	},
	[135] = {
		element_index = '人物配音',
		element_name = '玩家-赵云',
		sound_id = 135,
		sound_path = 'sound/npc_sound/npc_wanjia1_16.mp3',
		sound_type = 1,
	},
	[136] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 136,
		sound_path = 'sound/npc_sound/npc_wanjia2_12.mp3',
		sound_type = 1,
	},
	[137] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 137,
		sound_path = 'sound/npc_sound/npc_wanjia2_13.mp3',
		sound_type = 1,
	},
	[138] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 138,
		sound_path = 'sound/npc_sound/npc_wanjia2_14.mp3',
		sound_type = 1,
	},
	[139] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 139,
		sound_path = 'sound/npc_sound/npc_wanjia2_15.mp3',
		sound_type = 1,
	},
	[140] = {
		element_index = '人物配音',
		element_name = '玩家-诸葛',
		sound_id = 140,
		sound_path = 'sound/npc_sound/npc_wanjia2_16.mp3',
		sound_type = 1,
	},
	[141] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 141,
		sound_path = 'sound/npc_sound/npc_wanjia3_12.mp3',
		sound_type = 1,
	},
	[142] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 142,
		sound_path = 'sound/npc_sound/npc_wanjia3_13.mp3',
		sound_type = 1,
	},
	[143] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 143,
		sound_path = 'sound/npc_sound/npc_wanjia3_14.mp3',
		sound_type = 1,
	},
	[144] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 144,
		sound_path = 'sound/npc_sound/npc_wanjia3_15.mp3',
		sound_type = 1,
	},
	[145] = {
		element_index = '人物配音',
		element_name = '玩家-貂蝉',
		sound_id = 145,
		sound_path = 'sound/npc_sound/npc_wanjia3_16.mp3',
		sound_type = 1,
	},
	[146] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 146,
		sound_path = 'sound/npc_sound/npc_yunji_10.mp3',
		sound_type = 1,
	},
	[147] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 147,
		sound_path = 'sound/npc_sound/npc_yunji_11.mp3',
		sound_type = 1,
	},
	[148] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 148,
		sound_path = 'sound/npc_sound/npc_yunji_12.mp3',
		sound_type = 1,
	},
	[149] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 149,
		sound_path = 'sound/npc_sound/npc_yunji_13.mp3',
		sound_type = 1,
	},
	[150] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 150,
		sound_path = 'sound/npc_sound/npc_yunji_14.mp3',
		sound_type = 1,
	},
	[151] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 151,
		sound_path = 'sound/npc_sound/npc_yunji_15.mp3',
		sound_type = 1,
	},
	[152] = {
		element_index = '人物配音',
		element_name = '云姬',
		sound_id = 152,
		sound_path = 'sound/npc_sound/npc_yunji_16.mp3',
		sound_type = 1,
	},
	[10000] = {
		element_index = -1,
		element_name = -1,
		sound_id = 10000,
		sound_path = 'sound/bg_sound/sanguo_city1.mp3',
		sound_type = 0,
	},
	[10001] = {
		element_index = -1,
		element_name = -1,
		sound_id = 10001,
		sound_path = 'sound/bg_sound/sanguo_city1.mp3',
		sound_type = 0,
	},
	[10002] = {
		element_index = -1,
		element_name = -1,
		sound_id = 10002,
		sound_path = 'sound/bg_sound/sanguo_city2.mp3',
		sound_type = 0,
	},
	[10003] = {
		element_index = -1,
		element_name = -1,
		sound_id = 10003,
		sound_path = 'sound/bg_sound/zhandou.mp3',
		sound_type = 0,
	},
	[10004] = {
		element_index = -1,
		element_name = -1,
		sound_id = 10004,
		sound_path = 'sound/bg_sound/boss.mp3',
		sound_type = 0,
	},
	[10005] = {
		element_index = -1,
		element_name = -1,
		sound_id = 10005,
		sound_path = 'sound/bg_sound/pvp.mp3',
		sound_type = 0,
	},
	[10006] = {
		element_index = -1,
		element_name = -1,
		sound_id = 10006,
		sound_path = 'sound/bg_sound/sanguo_fight3.mp3',
		sound_type = 0,
	},
	[10007] = {
		element_index = -1,
		element_name = -1,
		sound_id = 10007,
		sound_path = 'sound/bg_sound/yunhai.mp3',
		sound_type = 0,
	},
	[20001] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20001,
		sound_path = 'sound/effect_sound/gongjisheng1.mp3',
		sound_type = 1,
	},
	[20002] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20002,
		sound_path = 'sound/effect_sound/gongjisheng2.mp3',
		sound_type = 1,
	},
	[20003] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20003,
		sound_path = 'sound/effect_sound/gongjisheng3.mp3',
		sound_type = 1,
	},
	[20004] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20004,
		sound_path = 'sound/effect_sound/mingzhongsheng1.mp3',
		sound_type = 1,
	},
	[20005] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20005,
		sound_path = 'sound/effect_sound/putonganniu.mp3',
		sound_type = 1,
	},
	[20006] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20006,
		sound_path = 'sound/effect_sound/putonganniu.mp3',
		sound_type = 1,
	},
	[20007] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20007,
		sound_path = 'sound/effect_sound/putonganniu.mp3',
		sound_type = 1,
	},
	[20008] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20008,
		sound_path = 'sound/effect_sound/huodewupin.mp3',
		sound_type = 1,
	},
	[20009] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20009,
		sound_path = 'sound/effect_sound/putonganniu.mp3',
		sound_type = 1,
	},
	[20010] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20010,
		sound_path = 'sound/effect_sound/caozuochenggong.mp3',
		sound_type = 1,
	},
	[20011] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20011,
		sound_path = 'sound/effect_sound/huodewupin.mp3',
		sound_type = 1,
	},
	[20012] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20012,
		sound_path = 'sound/effect_sound/putonganniu.mp3',
		sound_type = 1,
	},
	[20013] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20013,
		sound_path = 'sound/effect_sound/guaiwuxiaoshi.mp3',
		sound_type = 1,
	},
	[20014] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20014,
		sound_path = 'sound/effect_sound/huodewupin.mp3',
		sound_type = 1,
	},
	[20015] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20015,
		sound_path = 'sound/effect_sound/caozuochenggong.mp3',
		sound_type = 1,
	},
	[20016] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20016,
		sound_path = 'sound/effect_sound/caozuoshibai.mp3',
		sound_type = 1,
	},
	[20017] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20017,
		sound_path = 'sound/effect_sound/caozuochenggong.mp3',
		sound_type = 1,
	},
	[20018] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20018,
		sound_path = 'sound/effect_sound/ko.mp3',
		sound_type = 1,
	},
	[20019] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20019,
		sound_path = 'sound/effect_sound/guaiwuxiaoshi.mp3',
		sound_type = 1,
	},
	[20020] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20020,
		sound_path = 'sound/effect_sound/guangzhu.mp3',
		sound_type = 1,
	},
	[20021] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20021,
		sound_path = 'sound/effect_sound/shizijia.mp3',
		sound_type = 1,
	},
	[20022] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20022,
		sound_path = 'sound/effect_sound/anyingpoxiaoshi.mp3',
		sound_type = 1,
	},
	[20023] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20023,
		sound_path = 'sound/effect_sound/anyingpobaozha.mp3',
		sound_type = 1,
	},
	[20024] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20024,
		sound_path = 'sound/effect_sound/nengliangchongji1.mp3',
		sound_type = 1,
	},
	[20025] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20025,
		sound_path = 'sound/effect_sound/nengliangchongji2.mp3',
		sound_type = 1,
	},
	[20026] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20026,
		sound_path = 'sound/effect_sound/anyingpobaozha.mp3',
		sound_type = 1,
	},
	[20027] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20027,
		sound_path = 'sound/effect_sound/xuli.mp3',
		sound_type = 1,
	},
	[20028] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20028,
		sound_path = 'sound/effect_sound/bingbao.mp3',
		sound_type = 1,
	},
	[20029] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20029,
		sound_path = 'sound/effect_sound/hanliu.mp3',
		sound_type = 1,
	},
	[20030] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20030,
		sound_path = 'sound/effect_sound/shifangdazhao.mp3',
		sound_type = 1,
	},
	[20031] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20031,
		sound_path = 'sound/effect_sound/feijian1.mp3',
		sound_type = 1,
	},
	[20032] = {
		element_index = -1,
		element_name = -1,
		sound_id = 20032,
		sound_path = 'sound/effect_sound/feijian2.mp3',
		sound_type = 1,
	},
}
