CSV.tables.spx_source = {
	[100000001] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '主角',
		element_name = '主角赵云',
		id = 100000001,
		img = 'ccbResources/ani/zhujue_zy.png',
	},
	[100000002] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '主角',
		element_name = '主角诸葛亮',
		id = 100000002,
		img = 'ccbResources/ani/zhujue_zg.png',
	},
	[100000003] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '主角',
		element_name = '主角貂蝉',
		id = 100000003,
		img = 'ccbResources/ani/zhujue_dc.png',
	},
	[100000004] = {
		data = 'ccbResources/ani/daoguang_zy.sprite',
		element_index = '主角',
		element_name = '主角赵云刀光',
		id = 100000004,
		img = 'ccbResources/ani/daoguang_zy.png',
	},
	[100000005] = {
		data = 'ccbResources/ani/daoguang_zg.sprite',
		element_index = '主角',
		element_name = '主角诸葛亮刀光',
		id = 100000005,
		img = 'ccbResources/ani/daoguang_zg.png',
	},
	[100000006] = {
		data = 'ccbResources/ani/daoguang_dc.sprite',
		element_index = '主角',
		element_name = '主角貂蝉刀光',
		id = 100000006,
		img = 'ccbResources/ani/daoguang_dc.png',
	},
	[100000007] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云武器基本上',
		id = 100000007,
		img = 'ccbResources/ani/wuqi_zy_lv1.png',
	},
	[100000008] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云武器基本下',
		id = 100000008,
		img = 'ccbResources/ani/wuqi_zy_lv1.png',
	},
	[100000009] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛亮武器基本上',
		id = 100000009,
		img = 'ccbResources/ani/wuqi_zg_lv1.png',
	},
	[100000010] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛亮武器基本下',
		id = 100000010,
		img = 'ccbResources/ani/wuqi_zg_lv1.png',
	},
	[100000011] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉武器基本上',
		id = 100000011,
		img = 'ccbResources/ani/wuqi_dc_lv1.png',
	},
	[100000012] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉武器基本下',
		id = 100000012,
		img = 'ccbResources/ani/wuqi_dc_lv1.png',
	},
	[100000013] = {
		data = 'ccbResources/ani/zuoji_baima.sprite',
		element_index = '坐骑模型',
		element_name = '一阶白马',
		id = 100000013,
		img = 'ccbResources/ani/zuoji_baima.png',
	},
	[100000014] = {
		data = 'ccbResources/ani/zuoji_heima.sprite',
		element_index = '坐骑模型',
		element_name = '二阶幽冥马',
		id = 100000014,
		img = 'ccbResources/ani/zuoji_heima.png',
	},
	[100000015] = {
		data = 'ccbResources/ani/zuoji_baihu.sprite',
		element_index = '坐骑模型',
		element_name = '三阶白虎',
		id = 100000015,
		img = 'ccbResources/ani/zuoji_baihu.png',
	},
	[100000016] = {
		data = 'ccbResources/ani/zuoji_huli.sprite',
		element_index = '坐骑模型',
		element_name = '四阶九尾狐',
		id = 100000016,
		img = 'ccbResources/ani/zuoji_huli.png',
	},
	[100000017] = {
		data = 'ccbResources/ani/zuoji_xiyi.sprite',
		element_index = '坐骑模型',
		element_name = '五阶蜥蜴',
		id = 100000017,
		img = 'ccbResources/ani/zuoji_xiyi.png',
	},
	[100000018] = {
		data = 'ccbResources/ani/zuoji_longgui.sprite',
		element_index = '坐骑模型',
		element_name = '六阶玄武',
		id = 100000018,
		img = 'ccbResources/ani/zuoji_longgui.png',
	},
	[100000019] = {
		data = 'ccbResources/ani/zuoji_pixiu.sprite',
		element_index = '坐骑模型',
		element_name = '七阶貔貅',
		id = 100000019,
		img = 'ccbResources/ani/zuoji_pixiu.png',
	},
	[100000020] = {
		data = 'ccbResources/ani/zuoji_jiguanshou.sprite',
		element_index = '坐骑模型',
		element_name = '八阶木牛流马',
		id = 100000020,
		img = 'ccbResources/ani/zuoji_jiguanshou.png',
	},
	[100000021] = {
		data = 'ccbResources/ani/zuoji_jiashou.sprite',
		element_index = '坐骑模型',
		element_name = '九阶火炎兽',
		id = 100000021,
		img = 'ccbResources/ani/zuoji_jiashou.png',
	},
	[100000022] = {
		data = 'ccbResources/ani/zuoji_qilin.sprite',
		element_index = '坐骑模型',
		element_name = '十阶麒麟',
		id = 100000022,
		img = 'ccbResources/ani/zuoji_qilin.png',
	},
	[100000023] = {
		data = 'ccbResources/ani/guai_chunyudao.sprite',
		element_index = '怪物模型',
		element_name = '淳于导',
		id = 100000023,
		img = 'ccbResources/ani/guai_chunyudao.png',
	},
	[100000024] = {
		data = 'ccbResources/ani/guai_yanming.sprite',
		element_index = '怪物模型',
		element_name = '晏明',
		id = 100000024,
		img = 'ccbResources/ani/guai_yanming.png',
	},
	[100000025] = {
		data = 'ccbResources/ani/guai_zhenji.sprite',
		element_index = '怪物模型',
		element_name = '甄姬',
		id = 100000025,
		img = 'ccbResources/ani/guai_zhenji.png',
	},
	[100000026] = {
		data = 'ccbResources/ani/guai_xuhuang.sprite',
		element_index = '怪物模型',
		element_name = '徐晃',
		id = 100000026,
		img = 'ccbResources/ani/guai_xuhuang.png',
	},
	[100000027] = {
		data = 'ccbResources/ani/guai_zhangliao.sprite',
		element_index = '怪物模型',
		element_name = '张辽',
		id = 100000027,
		img = 'ccbResources/ani/guai_zhangliao.png',
	},
	[100000028] = {
		data = 'ccbResources/ani/guai_dazhuang.sprite',
		element_index = '怪物模型',
		element_name = '大壮',
		id = 100000028,
		img = 'ccbResources/ani/guai_dazhuang.png',
	},
	[100000029] = {
		data = 'ccbResources/ani/guai_feifei.sprite',
		element_index = '怪物模型',
		element_name = '肥肥',
		id = 100000029,
		img = 'ccbResources/ani/guai_feifei.png',
	},
	[100000030] = {
		data = 'ccbResources/ani/guai_gongjianbing.sprite',
		element_index = '怪物模型',
		element_name = '弓箭兵',
		id = 100000030,
		img = 'ccbResources/ani/guai_gongjianbing.png',
	},
	[100000031] = {
		data = 'ccbResources/ani/guai_huanggai.sprite',
		element_index = '怪物模型',
		element_name = '黄盖',
		id = 100000031,
		img = 'ccbResources/ani/guai_huanggai.png',
	},
	[100000032] = {
		data = 'ccbResources/ani/guai_lidian.sprite',
		element_index = '怪物模型',
		element_name = '李典',
		id = 100000032,
		img = 'ccbResources/ani/guai_lidian.png',
	},
	[100000033] = {
		data = 'ccbResources/ani/guai_lvbu.sprite',
		element_index = '怪物模型',
		element_name = '吕布',
		id = 100000033,
		img = 'ccbResources/ani/guai_lvbu.png',
	},
	[100000034] = {
		data = 'ccbResources/ani/guai_nvcike.sprite',
		element_index = '怪物模型',
		element_name = '女刺客',
		id = 100000034,
		img = 'ccbResources/ani/guai_nvcike.png',
	},
	[100000035] = {
		data = 'ccbResources/ani/guai_qiangbing.sprite',
		element_index = '怪物模型',
		element_name = '枪兵',
		id = 100000035,
		img = 'ccbResources/ani/guai_qiangbing.png',
	},
	[100000036] = {
		data = 'ccbResources/ani/guai_quanrenbing.sprite',
		element_index = '怪物模型',
		element_name = '拳刃兵',
		id = 100000036,
		img = 'ccbResources/ani/guai_quanrenbing.png',
	},
	[100000037] = {
		data = 'ccbResources/ani/guai_renzhe.sprite',
		element_index = '怪物模型',
		element_name = '忍者',
		id = 100000037,
		img = 'ccbResources/ani/guai_renzhe.png',
	},
	[100000038] = {
		data = 'ccbResources/ani/guai_xiahoudun.sprite',
		element_index = '怪物模型',
		element_name = '夏侯惇',
		id = 100000038,
		img = 'ccbResources/ani/guai_xiahoudun.png',
	},
	[100000039] = {
		data = 'ccbResources/ani/guai_xuchu.sprite',
		element_index = '怪物模型',
		element_name = '许褚',
		id = 100000039,
		img = 'ccbResources/ani/guai_xuchu.png',
	},
	[100000040] = {
		data = 'ccbResources/ani/guai_zuoci.sprite',
		element_index = '怪物模型',
		element_name = '左慈',
		id = 100000040,
		img = 'ccbResources/ani/guai_zuoci.png',
	},
	[100000041] = {
		data = 'ccbResources/ani/guai_huoqiangbing.sprite',
		element_index = '怪物模型',
		element_name = '火枪兵',
		id = 100000041,
		img = 'ccbResources/ani/guai_huoqiangbing.png',
	},
	[100000042] = {
		data = 'ccbResources/ani/guai_simayi.sprite',
		element_index = '怪物模型',
		element_name = '司马懿',
		id = 100000042,
		img = 'ccbResources/ani/guai_simayi.png',
	},
	[100000043] = {
		data = 'ccbResources/ani/guai_zhangjiao.sprite',
		element_index = '怪物模型',
		element_name = '张角',
		id = 100000043,
		img = 'ccbResources/ani/guai_zhangjiao.png',
	},
	[100000044] = {
		data = 'ccbResources/ani/guai_ganning.sprite',
		element_index = '怪物模型',
		element_name = '甘宁',
		id = 100000044,
		img = 'ccbResources/ani/guai_ganning.png',
	},
	[100000045] = {
		data = 'ccbResources/ani/guai_luxun.sprite',
		element_index = '怪物模型',
		element_name = '陆逊',
		id = 100000045,
		img = 'ccbResources/ani/guai_luxun.png',
	},
	[100000046] = {
		data = 'ccbResources/ani/guai_caocao.sprite',
		element_index = '怪物模型',
		element_name = '曹操Boss',
		id = 100000046,
		img = 'ccbResources/ani/guai_caocao.png',
	},
	[100000047] = {
		data = 'ccbResources/ani/guai_xuchu.sprite',
		element_index = '怪物模型',
		element_name = '预留',
		id = 100000047,
		img = 'ccbResources/ani/guai_xuchu.png',
	},
	[100000048] = {
		data = 'ccbResources/ani/tx_zy_shenglong.sprite',
		element_index = '主角特效',
		element_name = '赵云特效升龙',
		id = 100000048,
		img = 'ccbResources/ani/tx_zy_shenglong.png',
	},
	[100000049] = {
		data = 'ccbResources/ani/tx_zy_baozha.sprite',
		element_index = '主角特效',
		element_name = '赵云特效爆炸',
		id = 100000049,
		img = 'ccbResources/ani/tx_zy_baozha.png',
	},
	[100000050] = {
		data = 'ccbResources/ani/tx_ty_dabo.sprite',
		element_index = '主角特效',
		element_name = '赵云特效大波',
		id = 100000050,
		img = 'ccbResources/ani/tx_ty_dabo.png',
	},
	[100000051] = {
		data = 'ccbResources/ani/tx_zy_baozha.sprite',
		element_index = '主角特效',
		element_name = '赵云特效4',
		id = 100000051,
		img = 'ccbResources/ani/tx_zy_baozha.png',
	},
	[100000052] = {
		data = 'ccbResources/ani/tx_zy_baozha.sprite',
		element_index = '主角特效',
		element_name = '赵云特效5',
		id = 100000052,
		img = 'ccbResources/ani/tx_zy_baozha.png',
	},
	[100000053] = {
		data = 'ccbResources/ani/tx_zy_baozha.sprite',
		element_index = '主角特效',
		element_name = '赵云特效6',
		id = 100000053,
		img = 'ccbResources/ani/tx_zy_baozha.png',
	},
	[100000054] = {
		data = 'ccbResources/ani/tx_zy_baozha.sprite',
		element_index = '主角特效',
		element_name = '赵云特效7',
		id = 100000054,
		img = 'ccbResources/ani/tx_zy_baozha.png',
	},
	[100000055] = {
		data = 'ccbResources/ani/tx_zy_baozha.sprite',
		element_index = '主角特效',
		element_name = '赵云特效8',
		id = 100000055,
		img = 'ccbResources/ani/tx_zy_baozha.png',
	},
	[100000056] = {
		data = 'ccbResources/ani/tx_zy_baozha.sprite',
		element_index = '主角特效',
		element_name = '赵云特效9',
		id = 100000056,
		img = 'ccbResources/ani/tx_zy_baozha.png',
	},
	[100000057] = {
		data = 'ccbResources/ani/tx_zy_baozha.sprite',
		element_index = '主角特效',
		element_name = '赵云特效10',
		id = 100000057,
		img = 'ccbResources/ani/tx_zy_baozha.png',
	},
	[100000058] = {
		data = 'ccbResources/ani/tx_zg_bagua.sprite',
		element_index = '主角特效',
		element_name = '诸葛亮特效八卦',
		id = 100000058,
		img = 'ccbResources/ani/tx_zg_bagua.png',
	},
	[100000059] = {
		data = 'ccbResources/ani/tx_zg_dalongjuan.sprite',
		element_index = '主角特效',
		element_name = '诸葛亮特效大龙卷',
		id = 100000059,
		img = 'ccbResources/ani/tx_zg_dalongjuan.png',
	},
	[100000060] = {
		data = 'ccbResources/ani/tx_zg_shunyi.sprite',
		element_index = '主角特效',
		element_name = '诸葛亮特效瞬移',
		id = 100000060,
		img = 'ccbResources/ani/tx_zg_shunyi.png',
	},
	[100000061] = {
		data = 'ccbResources/ani/tx_zg_xiaolongjuan.sprite',
		element_index = '主角特效',
		element_name = '诸葛亮特效小龙卷',
		id = 100000061,
		img = 'ccbResources/ani/tx_zg_xiaolongjuan.png',
	},
	[100000062] = {
		data = 'ccbResources/ani/tx_zg_xuli.sprite',
		element_index = '主角特效',
		element_name = '诸葛亮特效蓄力',
		id = 100000062,
		img = 'ccbResources/ani/tx_zg_xuli.png',
	},
	[100000063] = {
		data = 'ccbResources/ani/tx_zg_bingzhen.sprite',
		element_index = '主角特效',
		element_name = '诸葛亮特效冰针',
		id = 100000063,
		img = 'ccbResources/ani/tx_zg_bingzhen.png',
	},
	[100000064] = {
		data = 'ccbResources/ani/tx_zg_huoniao.sprite',
		element_index = '主角特效',
		element_name = '诸葛亮特效火鸟',
		id = 100000064,
		img = 'ccbResources/ani/tx_zg_huoniao.png',
	},
	[100000065] = {
		data = 'ccbResources/ani/jianqi.sprite',
		element_index = '主角特效',
		element_name = '诸葛亮特效剑气',
		id = 100000065,
		img = 'ccbResources/ani/jianqi.png',
	},
	[100000066] = {
		data = 'ccbResources/ani/tx_zg_xiaolongjuan.sprite',
		element_index = '主角特效',
		element_name = '诸葛亮特效9',
		id = 100000066,
		img = 'ccbResources/ani/tx_zg_xiaolongjuan.png',
	},
	[100000067] = {
		data = 'ccbResources/ani/tx_zg_xiaolongjuan.sprite',
		element_index = '主角特效',
		element_name = '诸葛亮特效10',
		id = 100000067,
		img = 'ccbResources/ani/tx_zg_xiaolongjuan.png',
	},
	[100000068] = {
		data = 'ccbResources/ani/tx_dc_hudiebaozha.sprite',
		element_index = '主角特效',
		element_name = '貂蝉特效蝴蝶',
		id = 100000068,
		img = 'ccbResources/ani/tx_dc_hudiebaozha.png',
	},
	[100000069] = {
		data = 'ccbResources/ani/tx_dc_hongdaoguang.sprite',
		element_index = '主角特效',
		element_name = '貂蝉特效红色刀光',
		id = 100000069,
		img = 'ccbResources/ani/tx_dc_hongdaoguang.png',
	},
	[100000070] = {
		data = 'ani/tx_dc_xiahua.sprite',
		element_index = '主角特效',
		element_name = '貂蝉特效3',
		id = 100000070,
		img = 'ani/tx_dc_xiahua.png',
	},
	[100000071] = {
		data = 'ani/tx_dc_xiahua.sprite',
		element_index = '主角特效',
		element_name = '貂蝉特效4',
		id = 100000071,
		img = 'ani/tx_dc_xiahua.png',
	},
	[100000072] = {
		data = 'ani/tx_dc_xiahua.sprite',
		element_index = '主角特效',
		element_name = '貂蝉特效5',
		id = 100000072,
		img = 'ani/tx_dc_xiahua.png',
	},
	[100000073] = {
		data = 'ani/tx_dc_xiahua.sprite',
		element_index = '主角特效',
		element_name = '貂蝉特效6',
		id = 100000073,
		img = 'ani/tx_dc_xiahua.png',
	},
	[100000074] = {
		data = 'ani/tx_dc_xiahua.sprite',
		element_index = '主角特效',
		element_name = '貂蝉特效7',
		id = 100000074,
		img = 'ani/tx_dc_xiahua.png',
	},
	[100000075] = {
		data = 'ani/tx_dc_xiahua.sprite',
		element_index = '主角特效',
		element_name = '貂蝉特效8',
		id = 100000075,
		img = 'ani/tx_dc_xiahua.png',
	},
	[100000076] = {
		data = 'ani/tx_dc_xiahua.sprite',
		element_index = '主角特效',
		element_name = '貂蝉特效9',
		id = 100000076,
		img = 'ani/tx_dc_xiahua.png',
	},
	[100000077] = {
		data = 'ani/tx_dc_xiahua.sprite',
		element_index = '主角特效',
		element_name = '貂蝉特效10',
		id = 100000077,
		img = 'ani/tx_dc_xiahua.png',
	},
	[100000078] = {
		data = 'ccbResources/ani/tx_dazhuang.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效大壮攻击',
		id = 100000078,
		img = 'ccbResources/ani/tx_dazhuang.png',
	},
	[100000079] = {
		data = 'ccbResources/ani/tx_feifei_zhadan.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效肥肥攻击',
		id = 100000079,
		img = 'ccbResources/ani/tx_feifei_zhadan.png',
	},
	[100000080] = {
		data = 'ccbResources/ani/tx_feifei_chongci.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效肥肥攻击2',
		id = 100000080,
		img = 'ccbResources/ani/tx_feifei_chongci.png',
	},
	[100000081] = {
		data = 'ccbResources/ani/tx_gongjianshou.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效弓箭手',
		id = 100000081,
		img = 'ccbResources/ani/tx_gongjianshou.png',
	},
	[100000082] = {
		data = 'ccbResources/ani/tx_ty_guaidaoguang.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效枪兵',
		id = 100000082,
		img = 'ccbResources/ani/tx_ty_guaidaoguang.png',
	},
	[100000083] = {
		data = 'ccbResources/ani/tx_ty_huo.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效黄盖大火',
		id = 100000083,
		img = 'ccbResources/ani/tx_ty_huo.png',
	},
	[100000084] = {
		data = 'ccbResources/ani/tx_huanggai.sprite',
		element_index = '怪物特效',
		element_name = '黄盖小火武器',
		id = 100000084,
		img = 'ccbResources/ani/tx_huanggai.png',
	},
	[100000085] = {
		data = 'ccbResources/ani/tx_nvcike.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效女刺客',
		id = 100000085,
		img = 'ccbResources/ani/tx_nvcike.png',
	},
	[100000086] = {
		data = 'ccbResources/ani/tx_ty_tuci.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效拳刃兵',
		id = 100000086,
		img = 'ccbResources/ani/tx_ty_tuci.png',
	},
	[100000087] = {
		data = 'ccbResources/ani/tx_renzhe.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效忍者',
		id = 100000087,
		img = 'ccbResources/ani/tx_renzhe.png',
	},
	[100000088] = {
		data = 'ccbResources/ani/tx_zuoci_bingzhui.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效左慈冰',
		id = 100000088,
		img = 'ccbResources/ani/tx_zuoci_bingzhui.png',
	},
	[100000089] = {
		data = 'ccbResources/ani/tx_zuoci_huoqiu.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效左慈火',
		id = 100000089,
		img = 'ccbResources/ani/tx_zuoci_huoqiu.png',
	},
	[100000090] = {
		data = 'ccbResources/ani/tx_lvbu.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效吕布刀光',
		id = 100000090,
		img = 'ccbResources/ani/tx_lvbu.png',
	},
	[100000091] = {
		data = 'ccbResources/ani/tx_ty_shandian.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效吕布雷电',
		id = 100000091,
		img = 'ccbResources/ani/tx_ty_shandian.png',
	},
	[100000092] = {
		data = 'ccbResources/ani/tx_ty_zadi.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效砸地',
		id = 100000092,
		img = 'ccbResources/ani/tx_ty_zadi.png',
	},
	[100000093] = {
		data = 'ccbResources/ani/tx_lidian.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效李典飞脚',
		id = 100000093,
		img = 'ccbResources/ani/tx_lidian.png',
	},
	[100000094] = {
		data = 'ccbResources/ani/tx_xiahoudun.sprite',
		element_index = '怪物特效',
		element_name = '怪物特效夏侯惇攻击',
		id = 100000094,
		img = 'ccbResources/ani/tx_xiahoudun.png',
	},
	[100000095] = {
		data = 'ccbResources/ani/tx_ty_zhengtuo.sprite',
		element_index = '通用特效',
		element_name = '主角挣脱特效',
		id = 100000095,
		img = 'ccbResources/ani/tx_ty_zhengtuo.png',
	},
	[100000096] = {
		data = 'ccbResources/ani/tx_xianling.sprite',
		element_index = '通用特效',
		element_name = '仙灵技能召唤特效',
		id = 100000096,
		img = 'ccbResources/ani/tx_xianling.png',
	},
	[100000097] = {
		data = 'ccbResources/ani/xulitexiao.sprite',
		element_index = '通用特效',
		element_name = '蓄力特效',
		id = 100000097,
		img = 'ccbResources/ani/xulitexiao.png',
	},
	[100000098] = {
		data = 'ccbResources/ani/tx_ty_beigongji.sprite',
		element_index = '通用特效',
		element_name = '被攻击特效',
		id = 100000098,
		img = 'ccbResources/ani/tx_ty_beigongji.png',
	},
	[100000099] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器1级上',
		id = 100000099,
		img = 'ccbResources/ani/wuqi_zy_lv1.png',
	},
	[100000100] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器20级上',
		id = 100000100,
		img = 'ccbResources/ani/wuqi_zy_lv2.png',
	},
	[100000101] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器40级上',
		id = 100000101,
		img = 'ccbResources/ani/wuqi_zy_lv3.png',
	},
	[100000102] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器60级上',
		id = 100000102,
		img = 'ccbResources/ani/wuqi_zy_lv7.png',
	},
	[100000103] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器80级上',
		id = 100000103,
		img = 'ccbResources/ani/wuqi_zy_lv4.png',
	},
	[100000104] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵1级上',
		id = 100000104,
		img = 'ccbResources/ani/wuqi_zy_lv8.png',
	},
	[100000105] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵2级上',
		id = 100000105,
		img = 'ccbResources/ani/wuqi_zy_lv5.png',
	},
	[100000106] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵3级上',
		id = 100000106,
		img = 'ccbResources/ani/wuqi_zy_lv6.png',
	},
	[100000107] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵4级上',
		id = 100000107,
		img = 'ccbResources/ani/wuqi_zy_lv9.png',
	},
	[100000108] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵5级上',
		id = 100000108,
		img = 'ccbResources/ani/wuqi_zy_lv11.png',
	},
	[100000109] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵6级上',
		id = 100000109,
		img = 'ccbResources/ani/wuqi_zy_lv12.png',
	},
	[100000110] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵7级上',
		id = 100000110,
		img = 'ccbResources/ani/wuqi_zy_lv10.png',
	},
	[100000111] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器1级下',
		id = 100000111,
		img = 'ccbResources/ani/wuqi_zy_lv1.png',
	},
	[100000112] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器20级下',
		id = 100000112,
		img = 'ccbResources/ani/wuqi_zy_lv2.png',
	},
	[100000113] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器40级下',
		id = 100000113,
		img = 'ccbResources/ani/wuqi_zy_lv3.png',
	},
	[100000114] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器60级下',
		id = 100000114,
		img = 'ccbResources/ani/wuqi_zy_lv7.png',
	},
	[100000115] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器80级下',
		id = 100000115,
		img = 'ccbResources/ani/wuqi_zy_lv4.png',
	},
	[100000116] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵1级下',
		id = 100000116,
		img = 'ccbResources/ani/wuqi_zy_lv8.png',
	},
	[100000117] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵2级下',
		id = 100000117,
		img = 'ccbResources/ani/wuqi_zy_lv5.png',
	},
	[100000118] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵3级下',
		id = 100000118,
		img = 'ccbResources/ani/wuqi_zy_lv6.png',
	},
	[100000119] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵4级下',
		id = 100000119,
		img = 'ccbResources/ani/wuqi_zy_lv9.png',
	},
	[100000120] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵5级下',
		id = 100000120,
		img = 'ccbResources/ani/wuqi_zy_lv11.png',
	},
	[100000121] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵6级下',
		id = 100000121,
		img = 'ccbResources/ani/wuqi_zy_lv12.png',
	},
	[100000122] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵7级下',
		id = 100000122,
		img = 'ccbResources/ani/wuqi_zy_lv10.png',
	},
	[100000123] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器1级上',
		id = 100000123,
		img = 'ccbResources/ani/wuqi_zg_lv1.png',
	},
	[100000124] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器20级上',
		id = 100000124,
		img = 'ccbResources/ani/wuqi_zg_lv2.png',
	},
	[100000125] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器40级上',
		id = 100000125,
		img = 'ccbResources/ani/wuqi_zg_lv3.png',
	},
	[100000126] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器60级上',
		id = 100000126,
		img = 'ccbResources/ani/wuqi_zg_lv7.png',
	},
	[100000127] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器80级上',
		id = 100000127,
		img = 'ccbResources/ani/wuqi_zg_lv4.png',
	},
	[100000128] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵1级上',
		id = 100000128,
		img = 'ccbResources/ani/wuqi_zg_lv8.png',
	},
	[100000129] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵2级上',
		id = 100000129,
		img = 'ccbResources/ani/wuqi_zg_lv5.png',
	},
	[100000130] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵3级上',
		id = 100000130,
		img = 'ccbResources/ani/wuqi_zg_lv6.png',
	},
	[100000131] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵4级上',
		id = 100000131,
		img = 'ccbResources/ani/wuqi_zg_lv9.png',
	},
	[100000132] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵5级上',
		id = 100000132,
		img = 'ccbResources/ani/wuqi_zg_lv11.png',
	},
	[100000133] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵6级上',
		id = 100000133,
		img = 'ccbResources/ani/wuqi_zg_lv12.png',
	},
	[100000134] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵7级上',
		id = 100000134,
		img = 'ccbResources/ani/wuqi_zg_lv10.png',
	},
	[100000135] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器1级下',
		id = 100000135,
		img = 'ccbResources/ani/wuqi_zg_lv1.png',
	},
	[100000136] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器20级下',
		id = 100000136,
		img = 'ccbResources/ani/wuqi_zg_lv2.png',
	},
	[100000137] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器40级下',
		id = 100000137,
		img = 'ccbResources/ani/wuqi_zg_lv3.png',
	},
	[100000138] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器60级下',
		id = 100000138,
		img = 'ccbResources/ani/wuqi_zg_lv7.png',
	},
	[100000139] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器80级下',
		id = 100000139,
		img = 'ccbResources/ani/wuqi_zg_lv4.png',
	},
	[100000140] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵1级下',
		id = 100000140,
		img = 'ccbResources/ani/wuqi_zg_lv8.png',
	},
	[100000141] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵2级下',
		id = 100000141,
		img = 'ccbResources/ani/wuqi_zg_lv5.png',
	},
	[100000142] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵3级下',
		id = 100000142,
		img = 'ccbResources/ani/wuqi_zg_lv6.png',
	},
	[100000143] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵4级下',
		id = 100000143,
		img = 'ccbResources/ani/wuqi_zg_lv9.png',
	},
	[100000144] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵5级下',
		id = 100000144,
		img = 'ccbResources/ani/wuqi_zg_lv11.png',
	},
	[100000145] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵6级下',
		id = 100000145,
		img = 'ccbResources/ani/wuqi_zg_lv12.png',
	},
	[100000146] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵7级下',
		id = 100000146,
		img = 'ccbResources/ani/wuqi_zg_lv10.png',
	},
	[100000147] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器1级上',
		id = 100000147,
		img = 'ccbResources/ani/wuqi_dc_lv1.png',
	},
	[100000148] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器20级上',
		id = 100000148,
		img = 'ccbResources/ani/wuqi_dc_lv2.png',
	},
	[100000149] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器40级上',
		id = 100000149,
		img = 'ccbResources/ani/wuqi_dc_lv3.png',
	},
	[100000150] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器60级上',
		id = 100000150,
		img = 'ccbResources/ani/wuqi_dc_lv7.png',
	},
	[100000151] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器80级上',
		id = 100000151,
		img = 'ccbResources/ani/wuqi_dc_lv4.png',
	},
	[100000152] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵1级上',
		id = 100000152,
		img = 'ccbResources/ani/wuqi_dc_lv8.png',
	},
	[100000153] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵2级上',
		id = 100000153,
		img = 'ccbResources/ani/wuqi_dc_lv5.png',
	},
	[100000154] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵3级上',
		id = 100000154,
		img = 'ccbResources/ani/wuqi_dc_lv6.png',
	},
	[100000155] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵4级上',
		id = 100000155,
		img = 'ccbResources/ani/wuqi_dc_lv9.png',
	},
	[100000156] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵5级上',
		id = 100000156,
		img = 'ccbResources/ani/wuqi_dc_lv11.png',
	},
	[100000157] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵6级上',
		id = 100000157,
		img = 'ccbResources/ani/wuqi_dc_lv12.png',
	},
	[100000158] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵7级上',
		id = 100000158,
		img = 'ccbResources/ani/wuqi_dc_lv10.png',
	},
	[100000159] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器1级下',
		id = 100000159,
		img = 'ccbResources/ani/wuqi_dc_lv1.png',
	},
	[100000160] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器20级下',
		id = 100000160,
		img = 'ccbResources/ani/wuqi_dc_lv2.png',
	},
	[100000161] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器40级下',
		id = 100000161,
		img = 'ccbResources/ani/wuqi_dc_lv3.png',
	},
	[100000162] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器60级下',
		id = 100000162,
		img = 'ccbResources/ani/wuqi_dc_lv7.png',
	},
	[100000163] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器80级下',
		id = 100000163,
		img = 'ccbResources/ani/wuqi_dc_lv4.png',
	},
	[100000164] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵1级下',
		id = 100000164,
		img = 'ccbResources/ani/wuqi_dc_lv8.png',
	},
	[100000165] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵2级下',
		id = 100000165,
		img = 'ccbResources/ani/wuqi_dc_lv5.png',
	},
	[100000166] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵3级下',
		id = 100000166,
		img = 'ccbResources/ani/wuqi_dc_lv6.png',
	},
	[100000167] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵4级下',
		id = 100000167,
		img = 'ccbResources/ani/wuqi_dc_lv9.png',
	},
	[100000168] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵5级下',
		id = 100000168,
		img = 'ccbResources/ani/wuqi_dc_lv11.png',
	},
	[100000169] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵6级下',
		id = 100000169,
		img = 'ccbResources/ani/wuqi_dc_lv12.png',
	},
	[100000170] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵7级下',
		id = 100000170,
		img = 'ccbResources/ani/wuqi_dc_lv10.png',
	},
	[100000171] = {
		data = 'ccbResources/ani/npc_chuanlingbing.sprite',
		element_index = 'NPC',
		element_name = '传令兵',
		id = 100000171,
		img = 'ccbResources/ani/npc_chuanlingbing.png',
	},
	[100000172] = {
		data = 'ccbResources/ani/npc_diaochan.sprite',
		element_index = 'NPC',
		element_name = '貂蝉',
		id = 100000172,
		img = 'ccbResources/ani/npc_diaochan.png',
	},
	[100000173] = {
		data = 'ccbResources/ani/npc_guanyu.sprite',
		element_index = 'NPC',
		element_name = '关羽',
		id = 100000173,
		img = 'ccbResources/ani/npc_guanyu.png',
	},
	[100000174] = {
		data = 'ccbResources/ani/npc_liubei.sprite',
		element_index = 'NPC',
		element_name = '刘备',
		id = 100000174,
		img = 'ccbResources/ani/npc_liubei.png',
	},
	[100000175] = {
		data = 'ccbResources/ani/npc_sunshangxiang.sprite',
		element_index = 'NPC',
		element_name = '孙尚香',
		id = 100000175,
		img = 'ccbResources/ani/npc_sunshangxiang.png',
	},
	[100000176] = {
		data = 'ccbResources/ani/npc_xiaoqiao.sprite',
		element_index = 'NPC',
		element_name = '小乔',
		id = 100000176,
		img = 'ccbResources/ani/npc_xiaoqiao.png',
	},
	[100000177] = {
		data = 'ccbResources/ani/npc_zhangfei.sprite',
		element_index = 'NPC',
		element_name = '张飞',
		id = 100000177,
		img = 'ccbResources/ani/npc_zhangfei.png',
	},
	[100000178] = {
		data = 'ccbResources/ani/npc_zhaoyun.sprite',
		element_index = 'NPC',
		element_name = '赵云',
		id = 100000178,
		img = 'ccbResources/ani/npc_zhaoyun.png',
	},
	[100000179] = {
		data = 'ccbResources/ani/npc_zhugeliang.sprite',
		element_index = 'NPC',
		element_name = '诸葛亮',
		id = 100000179,
		img = 'ccbResources/ani/npc_zhugeliang.png',
	},
	[100000180] = {
		data = 'ccbResources/ani/tx_simayi_baozha.sprite',
		element_index = '怪物特效',
		element_name = '司马懿特效',
		id = 100000180,
		img = 'ccbResources/ani/tx_simayi_baozha.png',
	},
	[100000181] = {
		data = 'ccbResources/ani/tx_zhangjiao_kuloufazhen.sprite',
		element_index = '怪物特效',
		element_name = '张角骷髅法阵',
		id = 100000181,
		img = 'ccbResources/ani/tx_zhangjiao_kuloufazhen.png',
	},
	[100000182] = {
		data = 'ccbResources/ani/tx_zhangjiao_jinshenxuanzhuan.sprite',
		element_index = '怪物特效',
		element_name = '张角符文旋转',
		id = 100000182,
		img = 'ccbResources/ani/tx_zhangjiao_jinshenxuanzhuan.png',
	},
	[100000183] = {
		data = 'ccbResources/ani/tx_zhangjiao_dimianxuanwo.sprite',
		element_index = '怪物特效',
		element_name = '张角地面漩涡',
		id = 100000183,
		img = 'ccbResources/ani/tx_zhangjiao_dimianxuanwo.png',
	},
	[100000184] = {
		data = 'ccbResources/ani/tx_cuilian_zy1.sprite',
		element_index = '神兵淬炼特效',
		element_name = '赵云神兵淬炼特效1级',
		id = 100000184,
		img = 'ccbResources/ani/tx_cuilian_zy1.png',
	},
	[100000185] = {
		data = 'ccbResources/ani/tx_cuilian_zy2.sprite',
		element_index = '神兵淬炼特效',
		element_name = '赵云神兵淬炼特效2级',
		id = 100000185,
		img = 'ccbResources/ani/tx_cuilian_zy2.png',
	},
	[100000186] = {
		data = 'ccbResources/ani/tx_cuilian_zy3.sprite',
		element_index = '神兵淬炼特效',
		element_name = '赵云神兵淬炼特效3级',
		id = 100000186,
		img = 'ccbResources/ani/tx_cuilian_zy3.png',
	},
	[100000187] = {
		data = 'ccbResources/ani/tx_cuilian_zgl1.sprite',
		element_index = '神兵淬炼特效',
		element_name = '诸葛神兵淬炼特效1级',
		id = 100000187,
		img = 'ccbResources/ani/tx_cuilian_zgl1.png',
	},
	[100000188] = {
		data = 'ccbResources/ani/tx_cuilian_zgl2.sprite',
		element_index = '神兵淬炼特效',
		element_name = '诸葛神兵淬炼特效2级',
		id = 100000188,
		img = 'ccbResources/ani/tx_cuilian_zgl2.png',
	},
	[100000189] = {
		data = 'ccbResources/ani/tx_cuilian_zgl3.sprite',
		element_index = '神兵淬炼特效',
		element_name = '诸葛神兵淬炼特效3级',
		id = 100000189,
		img = 'ccbResources/ani/tx_cuilian_zgl3.png',
	},
	[100000190] = {
		data = 'ccbResources/ani/tx_cuilian_dc1.sprite',
		element_index = '神兵淬炼特效',
		element_name = '貂蝉神兵淬炼特效1级',
		id = 100000190,
		img = 'ccbResources/ani/tx_cuilian_dc1.png',
	},
	[100000191] = {
		data = 'ccbResources/ani/tx_cuilian_dc2.sprite',
		element_index = '神兵淬炼特效',
		element_name = '貂蝉神兵淬炼特效2级',
		id = 100000191,
		img = 'ccbResources/ani/tx_cuilian_dc2.png',
	},
	[100000192] = {
		data = 'ccbResources/ani/tx_cuilian_dc3.sprite',
		element_index = '神兵淬炼特效',
		element_name = '貂蝉神兵淬炼特效3级',
		id = 100000192,
		img = 'ccbResources/ani/tx_cuilian_dc3.png',
	},
	[100000193] = {
		data = 'ccbResources/ani/hulu.sprite',
		element_index = '怪物',
		element_name = '蓬莱仙境葫芦',
		id = 100000193,
		img = 'ccbResources/ani/hulu.png',
	},
	[100000194] = {
		data = 'ccbResources/ani/cw_shuijingma.sprite',
		element_index = '宠物',
		element_name = '小灵马',
		id = 100000194,
		img = 'ccbResources/ani/cw_shuijingma.png',
	},
	[100000195] = {
		data = 'ccbResources/ani/cw_linghu.sprite',
		element_index = '宠物',
		element_name = '小天狐',
		id = 100000195,
		img = 'ccbResources/ani/cw_linghu.png',
	},
	[100000196] = {
		data = 'ccbResources/ani/cw_baihu.sprite',
		element_index = '宠物',
		element_name = '小白虎',
		id = 100000196,
		img = 'ccbResources/ani/cw_baihu.png',
	},
	[100000197] = {
		data = 'ccbResources/ani/cw_xuanwu.sprite',
		element_index = '宠物',
		element_name = '小玄武',
		id = 100000197,
		img = 'ccbResources/ani/cw_xuanwu.png',
	},
	[100000198] = {
		data = 'ccbResources/ani/cw_qinglong.sprite',
		element_index = '宠物',
		element_name = '小青龙',
		id = 100000198,
		img = 'ccbResources/ani/cw_qinglong.png',
	},
	[100000199] = {
		data = 'ccbResources/ani/cw_zhuque.sprite',
		element_index = '宠物',
		element_name = '小朱雀',
		id = 100000199,
		img = 'ccbResources/ani/cw_zhuque.png',
	},
	[100000200] = {
		data = 'ccbResources/ani/jg_dici.sprite',
		element_index = '机关',
		element_name = '地刺',
		id = 100000200,
		img = 'ccbResources/ani/jg_dici.png',
	},
	[100000201] = {
		data = 'ccbResources/ani/jg_digou.sprite',
		element_index = '机关',
		element_name = '地沟',
		id = 100000201,
		img = 'ccbResources/ani/jg_digou.png',
	},
	[100000202] = {
		data = 'ccbResources/ani/jg_fukongpao.sprite',
		element_index = '机关',
		element_name = '浮空炮',
		id = 100000202,
		img = 'ccbResources/ani/jg_fukongpao.png',
	},
	[100000203] = {
		data = 'ccbResources/ani/jg_huozhu.sprite',
		element_index = '机关',
		element_name = '火柱',
		id = 100000203,
		img = 'ccbResources/ani/jg_huozhu.png',
	},
	[100000204] = {
		data = 'ccbResources/ani/jg_gunlun.sprite',
		element_index = '机关特效',
		element_name = '地沟滚轮',
		id = 100000204,
		img = 'ccbResources/ani/jg_gunlun.png',
	},
	[100000205] = {
		data = 'ccbResources/ani/jg_gunlun.sprite',
		element_index = '机关',
		element_name = '预留',
		id = 100000205,
		img = 'ccbResources/ani/jg_gunlun.png',
	},
	[100000206] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '主角时装',
		element_name = '赵云黄金甲',
		id = 100000206,
		img = 'ccbResources/ani/shizhuang_zy_huangjinjia.png',
	},
	[100000207] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '主角时装',
		element_name = '诸葛黄金甲',
		id = 100000207,
		img = 'ccbResources/ani/shizhuang_zg_huangjinjia.png',
	},
	[100000208] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '主角时装',
		element_name = '貂蝉黄金甲',
		id = 100000208,
		img = 'ccbResources/ani/shizhuang_dc_huangjinjia.png',
	},
	[100000209] = {
		data = 'ccbResources/ani/zuoqijineng_huzhua.sprite',
		element_index = '通用特效',
		element_name = '坐骑技能虎斩特效',
		id = 100000209,
		img = 'ccbResources/ani/zuoqijineng_huzhua.png',
	},
	[100000210] = {
		data = 'ccbResources/ani/zuoqijineng_huixuanbiao.sprite',
		element_index = '通用特效',
		element_name = '坐骑技能回旋镖特效',
		id = 100000210,
		img = 'ccbResources/ani/zuoqijineng_huixuanbiao.png',
	},
	[100000211] = {
		data = 'ccbResources/ani/zuoqijiaodiguangxiao.sprite',
		element_index = '通用特效',
		element_name = '坐骑脚底特效',
		id = 100000211,
		img = 'ccbResources/ani/zuoqijiaodiguangxiao.png',
	},
	[100000212] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '主角时装',
		element_name = '赵云修仙装',
		id = 100000212,
		img = 'ccbResources/ani/shizhuang_zy_xiuxian.png',
	},
	[100000213] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '主角时装',
		element_name = '诸葛修仙装',
		id = 100000213,
		img = 'ccbResources/ani/shizhuang_zg_xiuxian.png',
	},
	[100000214] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '主角时装',
		element_name = '貂蝉修仙装',
		id = 100000214,
		img = 'ccbResources/ani/shizhuang_dc_xiuxian.png',
	},
	[100000215] = {
		data = 'ccbResources/ani/tx_zhaohuan.sprite',
		element_index = '通用特效',
		element_name = '上马特效',
		id = 100000215,
		img = 'ccbResources/ani/tx_zhaohuan.png',
	},
	[100000216] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '主角时装',
		element_name = '赵云侠客装',
		id = 100000216,
		img = 'ccbResources/ani/shizhuang_zy_wuxia.png',
	},
	[100000217] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '主角时装',
		element_name = '诸葛侠客装',
		id = 100000217,
		img = 'ccbResources/ani/shizhuang_zg_wuxia.png',
	},
	[100000218] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '主角时装',
		element_name = '貂蝉侠客装',
		id = 100000218,
		img = 'ccbResources/ani/shizhuang_dc_wuxia.png',
	},
	[100000219] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '主角时装',
		element_name = '赵云萌宠装',
		id = 100000219,
		img = 'ccbResources/ani/shizhuang_zy_mengchong.png',
	},
	[100000220] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '主角时装',
		element_name = '诸葛萌宠装',
		id = 100000220,
		img = 'ccbResources/ani/shizhuang_zg_mengchong.png',
	},
	[100000221] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '主角时装',
		element_name = '貂蝉萌宠装',
		id = 100000221,
		img = 'ccbResources/ani/shizhuang_dc_mengchong.png',
	},
	[100000222] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '主角时装',
		element_name = '赵云传说装',
		id = 100000222,
		img = 'ccbResources/ani/shizhuang_zy_chuanshuo.png',
	},
	[100000223] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '主角时装',
		element_name = '诸葛传说装',
		id = 100000223,
		img = 'ccbResources/ani/shizhuang_zg_chuanshuo.png',
	},
	[100000224] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '主角时装',
		element_name = '貂蝉传说装',
		id = 100000224,
		img = 'ccbResources/ani/shizhuang_dc_chuanshuo.png',
	},
	[100000225] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '小秘书云姬',
		id = 100000225,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000226] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000226,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000227] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000227,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000228] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000228,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000229] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000229,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000230] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000230,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000231] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000231,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000232] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000232,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000233] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000233,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000234] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000234,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000235] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000235,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000236] = {
		data = 'ccbResources/ani/npc_kanbanniang.sprite',
		element_index = 'NPC',
		element_name = '预留',
		id = 100000236,
		img = 'ccbResources/ani/npc_kanbanniang.png',
	},
	[100000237] = {
		data = 'ccbResources/ani/npc_caiwenji.sprite',
		element_index = 'NPC',
		element_name = '蔡文姬',
		id = 100000237,
		img = 'ccbResources/ani/npc_caiwenji.png',
	},
	[100000238] = {
		data = 'ccbResources/ani/npc_caocao.sprite',
		element_index = 'NPC',
		element_name = '曹操',
		id = 100000238,
		img = 'ccbResources/ani/npc_caocao.png',
	},
	[100000239] = {
		data = 'ccbResources/ani/npc_huangyueying.sprite',
		element_index = 'NPC',
		element_name = '黄月英',
		id = 100000239,
		img = 'ccbResources/ani/npc_huangyueying.png',
	},
	[100000240] = {
		data = 'ccbResources/ani/npc_huangzhong.sprite',
		element_index = 'NPC',
		element_name = '黄忠',
		id = 100000240,
		img = 'ccbResources/ani/npc_huangzhong.png',
	},
	[100000241] = {
		data = 'ccbResources/ani/npc_machao.sprite',
		element_index = 'NPC',
		element_name = '马超',
		id = 100000241,
		img = 'ccbResources/ani/npc_machao.png',
	},
	[100000242] = {
		data = 'ccbResources/ani/npc_sunquan.sprite',
		element_index = 'NPC',
		element_name = '孙权',
		id = 100000242,
		img = 'ccbResources/ani/npc_sunquan.png',
	},
	[100000243] = {
		data = 'ccbResources/ani/npc_zhouyu.sprite',
		element_index = 'NPC',
		element_name = '周瑜',
		id = 100000243,
		img = 'ccbResources/ani/npc_zhouyu.png',
	},
	[100000244] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000244,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000245] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000245,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000246] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000246,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000247] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000247,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000248] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000248,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000249] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000249,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000250] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000250,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000251] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000251,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000252] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000252,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000253] = {
		data = 'ccbResources/ani/tx_yanming.sprite',
		element_index = '怪物特效',
		element_name = '晏明淳于导刀光',
		id = 100000253,
		img = 'ccbResources/ani/tx_yanming.png',
	},
	[100000254] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000254,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000255] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '预留',
		id = 100000255,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000256] = {
		data = 'ccbResources/ani/tx_xuhuang.sprite',
		element_index = '怪物特效',
		element_name = '徐晃旋转特效',
		id = 100000256,
		img = 'ccbResources/ani/tx_xuhuang.png',
	},
	[100000257] = {
		data = 'ccbResources/ani/tx_huoyanbo.sprite',
		element_index = '怪物特效',
		element_name = '火焰波特效',
		id = 100000257,
		img = 'ccbResources/ani/tx_huoyanbo.png',
	},
	[100000258] = {
		data = 'ccbResources/ani/chdt_xiaofuhao.sprite',
		element_index = '称号',
		element_name = '小富豪',
		id = 100000258,
		img = 'ccbResources/ani/chdt_xiaofuhao.png',
	},
	[100000259] = {
		data = 'ccbResources/ani/chdt_dashenhao.sprite',
		element_index = '称号',
		element_name = '大神豪',
		id = 100000259,
		img = 'ccbResources/ani/chdt_dashenhao.png',
	},
	[100000260] = {
		data = 'ccbResources/ani/chdt_zhizundiwang.sprite',
		element_index = '称号',
		element_name = '至尊帝王',
		id = 100000260,
		img = 'ccbResources/ani/chdt_zhizundiwang.png',
	},
	[100000261] = {
		data = 'ccbResources/ani/chdt_chuanshuogaoshou.sprite',
		element_index = '称号',
		element_name = '传说高手',
		id = 100000261,
		img = 'ccbResources/ani/chdt_chuanshuogaoshou.png',
	},
	[100000262] = {
		data = 'ccbResources/ani/chdt_xingyunzhishen.sprite',
		element_index = '称号',
		element_name = '幸运之神',
		id = 100000262,
		img = 'ccbResources/ani/chdt_xingyunzhishen.png',
	},
	[100000263] = {
		data = 'ccbResources/ani/chdt_huangdixinyi.sprite',
		element_index = '称号',
		element_name = '皇帝新衣',
		id = 100000263,
		img = 'ccbResources/ani/chdt_huangdixinyi.png',
	},
	[100000264] = {
		data = 'ccbResources/ani/tx_luxundaoguang.sprite',
		element_index = '怪物特效',
		element_name = '陆逊刀光武器',
		id = 100000264,
		img = 'ccbResources/ani/tx_luxundaoguang.png',
	},
	[100000265] = {
		data = 'ccbResources/ani/tx_luxunluanci.sprite',
		element_index = '怪物特效',
		element_name = '陆逊乱刺',
		id = 100000265,
		img = 'ccbResources/ani/tx_luxunluanci.png',
	},
	[100000266] = {
		data = 'ccbResources/ani/tx_zhangliaoxuanzhuandaoguang.sprite',
		element_index = '怪物特效',
		element_name = '张辽旋转',
		id = 100000266,
		img = 'ccbResources/ani/tx_zhangliaoxuanzhuandaoguang.png',
	},
	[100000267] = {
		data = 'ccbResources/ani/tx_zhangliaodaoguang.sprite',
		element_index = '怪物特效',
		element_name = '张辽刀光特效',
		id = 100000267,
		img = 'ccbResources/ani/tx_zhangliaodaoguang.png',
	},
	[100000268] = {
		data = 'ccbResources/ani/tx_daoguang_zhangliao.sprite',
		element_index = '怪物特效',
		element_name = '张辽幻影武器',
		id = 100000268,
		img = 'ccbResources/ani/tx_daoguang_zhangliao.png',
	},
	[100000269] = {
		data = 'ccbResources/ani/tx_ganningchongci.sprite',
		element_index = '怪物特效',
		element_name = '甘宁冲刺特效',
		id = 100000269,
		img = 'ccbResources/ani/tx_ganningchongci.png',
	},
	[100000270] = {
		data = 'ccbResources/ani/tx_daoguang_ganning.sprite',
		element_index = '怪物特效',
		element_name = '甘宁幻影武器',
		id = 100000270,
		img = 'ccbResources/ani/tx_daoguang_ganning.png',
	},
	[100000271] = {
		data = 'ccbResources/ani/tx_zhenji.sprite',
		element_index = '怪物特效',
		element_name = '甄姬技能',
		id = 100000271,
		img = 'ccbResources/ani/tx_zhenji.png',
	},
	[100000272] = {
		data = 'ccbResources/ani/tx_caocaodaoguang.sprite',
		element_index = '怪物特效',
		element_name = '曹操刀光特效',
		id = 100000272,
		img = 'ccbResources/ani/tx_caocaodaoguang.png',
	},
	[100000273] = {
		data = 'ccbResources/ani/tx_caocaobaozha.sprite',
		element_index = '怪物特效',
		element_name = '曹操爆炸特效',
		id = 100000273,
		img = 'ccbResources/ani/tx_caocaobaozha.png',
	},
	[100000274] = {
		data = 'ccbResources/ani/chdt_duyanluosha.sprite',
		element_index = '称号',
		element_name = '独眼罗刹',
		id = 100000274,
		img = 'ccbResources/ani/chdt_duyanluosha.png',
	},
	[100000275] = {
		data = 'ccbResources/ani/chdt_duyanluosha.sprite',
		element_index = '称号',
		element_name = '谜样之人',
		id = 100000275,
		img = 'ccbResources/ani/chdt_duyanluosha.png',
	},
	[100000276] = {
		data = 'ccbResources/ani/chdt_wushenbenzun.sprite',
		element_index = '称号',
		element_name = '武神本尊',
		id = 100000276,
		img = 'ccbResources/ani/chdt_wushenbenzun.png',
	},
	[100000277] = {
		data = 'ccbResources/ani/chdt_wanlangzhishou.sprite',
		element_index = '称号',
		element_name = '万狼之首',
		id = 100000277,
		img = 'ccbResources/ani/chdt_wanlangzhishou.png',
	},
	[100000278] = {
		data = 'ccbResources/ani/chdt_wendaoshenren.sprite',
		element_index = '称号',
		element_name = '问道真人',
		id = 100000278,
		img = 'ccbResources/ani/chdt_wendaoshenren.png',
	},
	[100000279] = {
		data = 'ccbResources/ani/guai_qiangbing_bianse.sprite',
		element_index = '怪物变色',
		element_name = '枪兵变色',
		id = 100000279,
		img = 'ccbResources/ani/guai_qiangbing_bianse.png',
	},
	[100000280] = {
		data = 'ccbResources/ani/guai_gongjianbing_bianse.sprite',
		element_index = '怪物变色',
		element_name = '弓箭手变色',
		id = 100000280,
		img = 'ccbResources/ani/guai_gongjianbing_bianse.png',
	},
	[100000281] = {
		data = 'ccbResources/ani/guai_quanrenbing_bianse.sprite',
		element_index = '怪物变色',
		element_name = '拳刃兵变色',
		id = 100000281,
		img = 'ccbResources/ani/guai_quanrenbing_bianse.png',
	},
	[100000282] = {
		data = 'ccbResources/ani/guai_nvcike_bianse.sprite',
		element_index = '怪物变色',
		element_name = '女刺客变色',
		id = 100000282,
		img = 'ccbResources/ani/guai_nvcike_bianse.png',
	},
	[100000283] = {
		data = 'ccbResources/ani/guai_renzhe_bianse.sprite',
		element_index = '怪物变色',
		element_name = '忍者变色',
		id = 100000283,
		img = 'ccbResources/ani/guai_renzhe_bianse.png',
	},
	[100000284] = {
		data = 'ccbResources/ani/guai_feifei_bianse.sprite',
		element_index = '怪物变色',
		element_name = '肥肥变色',
		id = 100000284,
		img = 'ccbResources/ani/guai_feifei_bianse.png',
	},
	[100000285] = {
		data = 'ccbResources/ani/guai_huoqiangbing_bianse.sprite',
		element_index = '怪物变色',
		element_name = '火枪兵变色',
		id = 100000285,
		img = 'ccbResources/ani/guai_huoqiangbing_bianse.png',
	},
	[100000286] = {
		data = 'ccbResources/ani/guai_dazhuang_bianse.sprite',
		element_index = '怪物变色',
		element_name = '大壮变色',
		id = 100000286,
		img = 'ccbResources/ani/guai_dazhuang_bianse.png',
	},
	[100000287] = {
		data = 'ccbResources/ani/guai_chunyudao_bianse.sprite',
		element_index = '怪物变色',
		element_name = '淳于导变色',
		id = 100000287,
		img = 'ccbResources/ani/guai_chunyudao_bianse.png',
	},
	[100000288] = {
		data = 'ccbResources/ani/guai_qiangbing_zhaobenshan.sprite',
		element_index = '怪物变外观',
		element_name = '枪兵变脸_赵本山',
		id = 100000288,
		img = 'ccbResources/ani/guai_qiangbing_zhaobenshan.png',
	},
	[100000289] = {
		data = 'ccbResources/ani/guai_qiangbing_guyanlong.sprite',
		element_index = '怪物变外观',
		element_name = '枪兵变脸_独眼龙',
		id = 100000289,
		img = 'ccbResources/ani/guai_qiangbing_guyanlong.png',
	},
	[100000290] = {
		data = 'ccbResources/ani/guai_qiangbing_heifa.sprite',
		element_index = '怪物变外观',
		element_name = '枪兵变脸_黑发',
		id = 100000290,
		img = 'ccbResources/ani/guai_qiangbing_heifa.png',
	},
	[100000291] = {
		data = 'ccbResources/ani/guai_qiangbing_bianwuqi1.sprite',
		element_index = '怪物变外观',
		element_name = '枪兵变武器_初级',
		id = 100000291,
		img = 'ccbResources/ani/guai_qiangbing_bianwuqi1.png',
	},
	[100000292] = {
		data = 'ccbResources/ani/guai_qiangbing_bianwuqi2.sprite',
		element_index = '怪物变外观',
		element_name = '枪兵变武器_中级',
		id = 100000292,
		img = 'ccbResources/ani/guai_qiangbing_bianwuqi2.png',
	},
	[100000293] = {
		data = 'ccbResources/ani/guai_qiangbing_bianwuqi3.sprite',
		element_index = '怪物变外观',
		element_name = '枪兵变武器_高级',
		id = 100000293,
		img = 'ccbResources/ani/guai_qiangbing_bianwuqi3.png',
	},
	[100000294] = {
		data = 'ccbResources/ani/guai_gongjianbing_xiaohuzi.sprite',
		element_index = '怪物变外观',
		element_name = '弓箭手变脸_小胡子',
		id = 100000294,
		img = 'ccbResources/ani/guai_gongjianbing_xiaohuzi.png',
	},
	[100000295] = {
		data = 'ccbResources/ani/guai_quanrenbing_duyan.sprite',
		element_index = '怪物变外观',
		element_name = '拳刃兵变脸_独眼龙',
		id = 100000295,
		img = 'ccbResources/ani/guai_quanrenbing_duyan.png',
	},
	[100000296] = {
		data = 'ccbResources/ani/guai_quanrenbing_xigua.sprite',
		element_index = '怪物变外观',
		element_name = '拳刃兵变脸_西瓜',
		id = 100000296,
		img = 'ccbResources/ani/guai_quanrenbing_xigua.png',
	},
	[100000297] = {
		data = 'ccbResources/ani/guai_quanrenbing_bianwuqi1.sprite',
		element_index = '怪物变外观',
		element_name = '拳刃兵变武器_初级',
		id = 100000297,
		img = 'ccbResources/ani/guai_quanrenbing_bianwuqi1.png',
	},
	[100000298] = {
		data = 'ccbResources/ani/guai_quanrenbing_bianwuqi2.sprite',
		element_index = '怪物变外观',
		element_name = '拳刃兵变武器_中级',
		id = 100000298,
		img = 'ccbResources/ani/guai_quanrenbing_bianwuqi2.png',
	},
	[100000299] = {
		data = 'ccbResources/ani/guai_quanrenbing_bianwuqi3.sprite',
		element_index = '怪物变外观',
		element_name = '拳刃兵变武器_高级',
		id = 100000299,
		img = 'ccbResources/ani/guai_quanrenbing_bianwuqi3.png',
	},
	[100000300] = {
		data = 'ccbResources/ani/guai_nvcike_shuangmawei.sprite',
		element_index = '怪物变外观',
		element_name = '女刺客变脸_双马尾',
		id = 100000300,
		img = 'ccbResources/ani/guai_nvcike_shuangmawei.png',
	},
	[100000301] = {
		data = 'ccbResources/ani/guai_renzhe_lanfa.sprite',
		element_index = '怪物变外观',
		element_name = '忍者变脸_蓝发',
		id = 100000301,
		img = 'ccbResources/ani/guai_renzhe_lanfa.png',
	},
	[100000302] = {
		data = 'ccbResources/ani/guai_renzhe_heifa.sprite',
		element_index = '怪物变外观',
		element_name = '忍者变脸_黑发',
		id = 100000302,
		img = 'ccbResources/ani/guai_renzhe_heifa.png',
	},
	[100000303] = {
		data = 'ccbResources/ani/guai_renzhe_bianwuqi.sprite',
		element_index = '怪物变外观',
		element_name = '忍者变武器',
		id = 100000303,
		img = 'ccbResources/ani/guai_renzhe_bianwuqi.png',
	},
	[100000304] = {
		data = 'ccbResources/ani/guai_huoqiangbing_bianwuqi1.sprite',
		element_index = '怪物变外观',
		element_name = '火枪兵变武器_初级',
		id = 100000304,
		img = 'ccbResources/ani/guai_huoqiangbing_bianwuqi1.png',
	},
	[100000305] = {
		data = 'ccbResources/ani/guai_huoqiangbing_bianwuqi2.sprite',
		element_index = '怪物变外观',
		element_name = '火枪兵变武器_中级',
		id = 100000305,
		img = 'ccbResources/ani/guai_huoqiangbing_bianwuqi2.png',
	},
	[100000306] = {
		data = 'ccbResources/ani/guai_huoqiangbing_bianwuqi3.sprite',
		element_index = '怪物变外观',
		element_name = '火枪兵变武器_高级',
		id = 100000306,
		img = 'ccbResources/ani/guai_huoqiangbing_bianwuqi3.png',
	},
	[100000307] = {
		data = 'ccbResources/ani/guai_feifei_xiong.sprite',
		element_index = '怪物变外观',
		element_name = '肥肥变脸_凶狠',
		id = 100000307,
		img = 'ccbResources/ani/guai_feifei_xiong.png',
	},
	[100000308] = {
		data = 'ccbResources/ani/guai_dazhuang_didi.sprite',
		element_index = '怪物变外观',
		element_name = '大壮变脸_弟弟',
		id = 100000308,
		img = 'ccbResources/ani/guai_dazhuang_didi.png',
	},
	[100000309] = {
		data = 'ccbResources/ani/guai_dazhuang_gege.sprite',
		element_index = '怪物变外观',
		element_name = '大壮变脸_哥哥',
		id = 100000309,
		img = 'ccbResources/ani/guai_dazhuang_gege.png',
	},
	[100000310] = {
		data = 'ccbResources/ani/guai_dazhuang_jitou.sprite',
		element_index = '怪物变外观',
		element_name = '大壮武器_鸡头',
		id = 100000310,
		img = 'ccbResources/ani/guai_dazhuang_jitou.png',
	},
	[100000311] = {
		data = 'ccbResources/ani/guai_dazhuang_zuichun.sprite',
		element_index = '怪物变外观',
		element_name = '大壮武器_嘴唇',
		id = 100000311,
		img = 'ccbResources/ani/guai_dazhuang_zuichun.png',
	},
	[100000312] = {
		data = 'ccbResources/ani/tp_duihua_banshen_zhaoyun.sprite',
		element_index = 'NPC表情',
		element_name = '主角赵云',
		id = 100000312,
		img = 'ccbResources/ani/tp_duihua_banshen_zhaoyun.png',
	},
	[100000313] = {
		data = 'ccbResources/ani/tp_duihua_banshen_zhugeliang.sprite',
		element_index = 'NPC表情',
		element_name = '主角诸葛',
		id = 100000313,
		img = 'ccbResources/ani/tp_duihua_banshen_zhugeliang.png',
	},
	[100000314] = {
		data = 'ccbResources/ani/tp_duihua_banshen_diaochan.sprite',
		element_index = 'NPC表情',
		element_name = '主角貂蝉',
		id = 100000314,
		img = 'ccbResources/ani/tp_duihua_banshen_diaochan.png',
	},
	[100000315] = {
		data = 'ccbResources/ani/tp_duihua_npccaiwenji.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC蔡文姬',
		id = 100000315,
		img = 'ccbResources/ani/tp_duihua_npccaiwenji.png',
	},
	[100000316] = {
		data = 'ccbResources/ani/tp_duihua_npccaocao.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC曹操',
		id = 100000316,
		img = 'ccbResources/ani/tp_duihua_npccaocao.png',
	},
	[100000317] = {
		data = 'ccbResources/ani/tp_duihua_npcchuanlingbing.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC传令兵',
		id = 100000317,
		img = 'ccbResources/ani/tp_duihua_npcchuanlingbing.png',
	},
	[100000318] = {
		data = 'ccbResources/ani/tp_duihua_npcguanyu.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC关羽',
		id = 100000318,
		img = 'ccbResources/ani/tp_duihua_npcguanyu.png',
	},
	[100000319] = {
		data = 'ccbResources/ani/tp_duihua_npchuangyueying.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC黄月英',
		id = 100000319,
		img = 'ccbResources/ani/tp_duihua_npchuangyueying.png',
	},
	[100000320] = {
		data = 'ccbResources/ani/tp_duihua_npchuangzhong.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC黄忠',
		id = 100000320,
		img = 'ccbResources/ani/tp_duihua_npchuangzhong.png',
	},
	[100000321] = {
		data = 'ccbResources/ani/tp_duihua_npckanbanniang.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC看板娘',
		id = 100000321,
		img = 'ccbResources/ani/tp_duihua_npckanbanniang.png',
	},
	[100000322] = {
		data = 'ccbResources/ani/tp_duihua_npcliubei.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC刘备',
		id = 100000322,
		img = 'ccbResources/ani/tp_duihua_npcliubei.png',
	},
	[100000323] = {
		data = 'ccbResources/ani/tp_duihua_npcmachao.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC马超',
		id = 100000323,
		img = 'ccbResources/ani/tp_duihua_npcmachao.png',
	},
	[100000324] = {
		data = 'ccbResources/ani/tp_duihua_npcsunquan.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC孙权',
		id = 100000324,
		img = 'ccbResources/ani/tp_duihua_npcsunquan.png',
	},
	[100000325] = {
		data = 'ccbResources/ani/tp_duihua_npcsunshangxiang.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC孙尚香',
		id = 100000325,
		img = 'ccbResources/ani/tp_duihua_npcsunshangxiang.png',
	},
	[100000326] = {
		data = 'ccbResources/ani/tp_duihua_npcxiaoqiao.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC小乔',
		id = 100000326,
		img = 'ccbResources/ani/tp_duihua_npcxiaoqiao.png',
	},
	[100000327] = {
		data = 'ccbResources/ani/tp_duihua_npczhangfei.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC张飞',
		id = 100000327,
		img = 'ccbResources/ani/tp_duihua_npczhangfei.png',
	},
	[100000328] = {
		data = 'ccbResources/ani/tp_duihua_npczhouyu.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC周瑜',
		id = 100000328,
		img = 'ccbResources/ani/tp_duihua_npczhouyu.png',
	},
	[100000329] = {
		data = 'ccbResources/ani/tp_duihua_npczhaoyun.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC赵云',
		id = 100000329,
		img = 'ccbResources/ani/tp_duihua_npczhaoyun.png',
	},
	[100000330] = {
		data = 'ccbResources/ani/tp_duihua_npcdiaochan.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC貂蝉',
		id = 100000330,
		img = 'ccbResources/ani/tp_duihua_npcdiaochan.png',
	},
	[100000331] = {
		data = 'ccbResources/ani/tp_duihua_npczhugeliang.sprite',
		element_index = 'NPC表情',
		element_name = 'NPC诸葛亮',
		id = 100000331,
		img = 'ccbResources/ani/tp_duihua_npczhugeliang.png',
	},
	[100000332] = {
		data = 'ccbResources/ani/tp_duihua_npcchunyudao.sprite',
		element_index = 'NPC表情',
		element_name = '淳于导',
		id = 100000332,
		img = 'ccbResources/ani/tp_duihua_npcchunyudao.png',
	},
	[100000333] = {
		data = 'ccbResources/ani/tp_duihua_npcdazhuang.sprite',
		element_index = 'NPC表情',
		element_name = '大壮',
		id = 100000333,
		img = 'ccbResources/ani/tp_duihua_npcdazhuang.png',
	},
	[100000334] = {
		data = 'ccbResources/ani/tp_duihua_npcfeifei.sprite',
		element_index = 'NPC表情',
		element_name = '肥肥',
		id = 100000334,
		img = 'ccbResources/ani/tp_duihua_npcfeifei.png',
	},
	[100000335] = {
		data = 'ccbResources/ani/tp_duihua_npcganning.sprite',
		element_index = 'NPC表情',
		element_name = '甘宁',
		id = 100000335,
		img = 'ccbResources/ani/tp_duihua_npcganning.png',
	},
	[100000336] = {
		data = 'ccbResources/ani/tp_duihua_npcgongjianbing.sprite',
		element_index = 'NPC表情',
		element_name = '弓箭兵',
		id = 100000336,
		img = 'ccbResources/ani/tp_duihua_npcgongjianbing.png',
	},
	[100000337] = {
		data = 'ccbResources/ani/tp_duihua_npchuanggai.sprite',
		element_index = 'NPC表情',
		element_name = '黄盖',
		id = 100000337,
		img = 'ccbResources/ani/tp_duihua_npchuanggai.png',
	},
	[100000338] = {
		data = 'ccbResources/ani/tp_duihua_npchuoqiangbing.sprite',
		element_index = 'NPC表情',
		element_name = '火枪兵',
		id = 100000338,
		img = 'ccbResources/ani/tp_duihua_npchuoqiangbing.png',
	},
	[100000339] = {
		data = 'ccbResources/ani/tp_duihua_npclidian.sprite',
		element_index = 'NPC表情',
		element_name = '李典',
		id = 100000339,
		img = 'ccbResources/ani/tp_duihua_npclidian.png',
	},
	[100000340] = {
		data = 'ccbResources/ani/tp_duihua_npcluxun.sprite',
		element_index = 'NPC表情',
		element_name = '陆逊',
		id = 100000340,
		img = 'ccbResources/ani/tp_duihua_npcluxun.png',
	},
	[100000341] = {
		data = 'ccbResources/ani/tp_duihua_npclvbu.sprite',
		element_index = 'NPC表情',
		element_name = '吕布',
		id = 100000341,
		img = 'ccbResources/ani/tp_duihua_npclvbu.png',
	},
	[100000342] = {
		data = 'ccbResources/ani/tp_duihua_npcnvcike.sprite',
		element_index = 'NPC表情',
		element_name = '女刺客',
		id = 100000342,
		img = 'ccbResources/ani/tp_duihua_npcnvcike.png',
	},
	[100000343] = {
		data = 'ccbResources/ani/tp_duihua_npcqiangbing.sprite',
		element_index = 'NPC表情',
		element_name = '枪兵',
		id = 100000343,
		img = 'ccbResources/ani/tp_duihua_npcqiangbing.png',
	},
	[100000344] = {
		data = 'ccbResources/ani/tp_duihua_npcquanrenbing.sprite',
		element_index = 'NPC表情',
		element_name = '拳刃兵',
		id = 100000344,
		img = 'ccbResources/ani/tp_duihua_npcquanrenbing.png',
	},
	[100000345] = {
		data = 'ccbResources/ani/tp_duihua_npcrenzhe.sprite',
		element_index = 'NPC表情',
		element_name = '忍者',
		id = 100000345,
		img = 'ccbResources/ani/tp_duihua_npcrenzhe.png',
	},
	[100000346] = {
		data = 'ccbResources/ani/tp_duihua_npcxiahoudun.sprite',
		element_index = 'NPC表情',
		element_name = '夏侯惇',
		id = 100000346,
		img = 'ccbResources/ani/tp_duihua_npcxiahoudun.png',
	},
	[100000347] = {
		data = 'ccbResources/ani/tp_duihua_npcxuhuang.sprite',
		element_index = 'NPC表情',
		element_name = '徐晃',
		id = 100000347,
		img = 'ccbResources/ani/tp_duihua_npcxuhuang.png',
	},
	[100000348] = {
		data = 'ccbResources/ani/tp_duihua_npcxuchu.sprite',
		element_index = 'NPC表情',
		element_name = '许褚',
		id = 100000348,
		img = 'ccbResources/ani/tp_duihua_npcxuchu.png',
	},
	[100000349] = {
		data = 'ccbResources/ani/tp_duihua_npcyanming.sprite',
		element_index = 'NPC表情',
		element_name = '晏明',
		id = 100000349,
		img = 'ccbResources/ani/tp_duihua_npcyanming.png',
	},
	[100000350] = {
		data = 'ccbResources/ani/tp_duihua_npczhangjiao.sprite',
		element_index = 'NPC表情',
		element_name = '张角',
		id = 100000350,
		img = 'ccbResources/ani/tp_duihua_npczhangjiao.png',
	},
	[100000351] = {
		data = 'ccbResources/ani/tp_duihua_npczhangliao.sprite',
		element_index = 'NPC表情',
		element_name = '张辽',
		id = 100000351,
		img = 'ccbResources/ani/tp_duihua_npczhangliao.png',
	},
	[100000352] = {
		data = 'ccbResources/ani/tp_duihua_npczhenji.sprite',
		element_index = 'NPC表情',
		element_name = '甄姬',
		id = 100000352,
		img = 'ccbResources/ani/tp_duihua_npczhenji.png',
	},
	[100000353] = {
		data = 'ccbResources/ani/tp_duihua_npczuoci.sprite',
		element_index = 'NPC表情',
		element_name = '左慈',
		id = 100000353,
		img = 'ccbResources/ani/tp_duihua_npczuoci.png',
	},
	[100000354] = {
		data = 'ccbResources/ani/tp_duihua_npcmowangcaocao.sprite',
		element_index = 'NPC表情',
		element_name = '魔王曹操',
		id = 100000354,
		img = 'ccbResources/ani/tp_duihua_npcmowangcaocao.png',
	},
	[100000355] = {
		data = 'ccbResources/ani/chdt_duyanluosha.sprite',
		element_index = '称号',
		element_name = '独眼罗刹',
		id = 100000355,
		img = 'ccbResources/ani/chdt_duyanluosha.png',
	},
	[100000356] = {
		data = 'ccbResources/ani/chdt_wushenbenzun.sprite',
		element_index = '称号',
		element_name = '武神本尊',
		id = 100000356,
		img = 'ccbResources/ani/chdt_wushenbenzun.png',
	},
	[100000357] = {
		data = 'ccbResources/ani/chdt_miyangzhiren.sprite',
		element_index = '称号',
		element_name = '谜样之人',
		id = 100000357,
		img = 'ccbResources/ani/chdt_miyangzhiren.png',
	},
	[100000358] = {
		data = 'ccbResources/ani/chdt_wanlangzhishou.sprite',
		element_index = '称号',
		element_name = '万狼之首',
		id = 100000358,
		img = 'ccbResources/ani/chdt_wanlangzhishou.png',
	},
	[100000359] = {
		data = 'ccbResources/ani/chdt_wendaoshenren.sprite',
		element_index = '称号',
		element_name = '问道神人',
		id = 100000359,
		img = 'ccbResources/ani/chdt_wendaoshenren.png',
	},
	[100000360] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '时装',
		element_name = '赵云魏国装',
		id = 100000360,
		img = 'ccbResources/ani/shizhuang_zy_weiguo.png',
	},
	[100000361] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '时装',
		element_name = '赵云蜀国装',
		id = 100000361,
		img = 'ccbResources/ani/shizhuang_zy_shuguo.png',
	},
	[100000362] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '时装',
		element_name = '赵云吴国装',
		id = 100000362,
		img = 'ccbResources/ani/shizhuang_zy_wuguo.png',
	},
	[100000363] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '时装',
		element_name = '赵云赤炎服',
		id = 100000363,
		img = 'ccbResources/ani/shizhuang_zy_xiuxianhong.png',
	},
	[100000364] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '时装',
		element_name = '赵云紫狂服',
		id = 100000364,
		img = 'ccbResources/ani/shizhuang_zy_xiuxianzi.png',
	},
	[100000365] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '时装',
		element_name = '赵云白鹤服',
		id = 100000365,
		img = 'ccbResources/ani/shizhuang_zy_xiuxianyin.png',
	},
	[100000366] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '时装',
		element_name = '赵云皇月服',
		id = 100000366,
		img = 'ccbResources/ani/shizhuang_zy_xiuxianhuang.png',
	},
	[100000367] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '时装',
		element_name = '赵云黑王服',
		id = 100000367,
		img = 'ccbResources/ani/shizhuang_zy_xiuxianhei.png',
	},
	[100000368] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '时装',
		element_name = '诸葛魏国装',
		id = 100000368,
		img = 'ccbResources/ani/shizhuang_zg_weiguo.png',
	},
	[100000369] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '时装',
		element_name = '诸葛蜀国装',
		id = 100000369,
		img = 'ccbResources/ani/shizhuang_zg_shuguo.png',
	},
	[100000370] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '时装',
		element_name = '诸葛吴国装',
		id = 100000370,
		img = 'ccbResources/ani/shizhuang_zg_wuguo.png',
	},
	[100000371] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '时装',
		element_name = '诸葛赤炎服',
		id = 100000371,
		img = 'ccbResources/ani/shizhuang_zg_xiuxianhong.png',
	},
	[100000372] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '时装',
		element_name = '诸葛紫狂服',
		id = 100000372,
		img = 'ccbResources/ani/shizhuang_zg_xiuxianzi.png',
	},
	[100000373] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '时装',
		element_name = '诸葛白鹤服',
		id = 100000373,
		img = 'ccbResources/ani/shizhuang_zg_xiuxianyin.png',
	},
	[100000374] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '时装',
		element_name = '诸葛皇月服',
		id = 100000374,
		img = 'ccbResources/ani/shizhuang_zg_xiuxianhuang.png',
	},
	[100000375] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '时装',
		element_name = '诸葛黑王服',
		id = 100000375,
		img = 'ccbResources/ani/shizhuang_zg_xiuxianhei.png',
	},
	[100000376] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '时装',
		element_name = '貂蝉魏国装',
		id = 100000376,
		img = 'ccbResources/ani/shizhuang_dc_weiguo.png',
	},
	[100000377] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '时装',
		element_name = '貂蝉蜀国装',
		id = 100000377,
		img = 'ccbResources/ani/shizhuang_dc_shuguo.png',
	},
	[100000378] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '时装',
		element_name = '貂蝉吴国装',
		id = 100000378,
		img = 'ccbResources/ani/shizhuang_dc_wuguo.png',
	},
	[100000379] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '时装',
		element_name = '貂蝉赤炎服',
		id = 100000379,
		img = 'ccbResources/ani/shizhuang_dc_xiuxianhong.png',
	},
	[100000380] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '时装',
		element_name = '貂蝉紫狂服',
		id = 100000380,
		img = 'ccbResources/ani/shizhuang_dc_xiuxianzi.png',
	},
	[100000381] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '时装',
		element_name = '貂蝉白鹤服',
		id = 100000381,
		img = 'ccbResources/ani/shizhuang_dc_xiuxianyin.png',
	},
	[100000382] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '时装',
		element_name = '貂蝉皇月服',
		id = 100000382,
		img = 'ccbResources/ani/shizhuang_dc_xiuxianhuang.png',
	},
	[100000383] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '时装',
		element_name = '貂蝉黑王服',
		id = 100000383,
		img = 'ccbResources/ani/shizhuang_dc_xiuxianhei.png',
	},
	[100000384] = {
		data = 'ccbResources/ani/zhujue_zy.sprite',
		element_index = '时装',
		element_name = '赵云天宫装',
		id = 100000384,
		img = 'ccbResources/ani/shizhuang_zy_shenjiang.png',
	},
	[100000385] = {
		data = 'ccbResources/ani/zhujue_zg.sprite',
		element_index = '时装',
		element_name = '诸葛天宫装',
		id = 100000385,
		img = 'ccbResources/ani/shizhuang_zg_shenjiang.png',
	},
	[100000386] = {
		data = 'ccbResources/ani/zhujue_dc.sprite',
		element_index = '时装',
		element_name = '貂蝉天宫装',
		id = 100000386,
		img = 'ccbResources/ani/shizhuang_dc_shenjiang.png',
	},
	[100000387] = {
		data = 'ccbResources/ani/cw_guguniao.sprite',
		element_index = '宠物',
		element_name = '小大鹏',
		id = 100000387,
		img = 'ccbResources/ani/cw_guguniao.png',
	},
	[100000388] = {
		data = 'ccbResources/ani/cw_wukong.sprite',
		element_index = '宠物',
		element_name = '小空空',
		id = 100000388,
		img = 'ccbResources/ani/cw_wukong.png',
	},
	[100000389] = {
		data = 'ccbResources/ani/cw_jinqianbao.sprite',
		element_index = '宠物',
		element_name = '小金豹',
		id = 100000389,
		img = 'ccbResources/ani/cw_jinqianbao.png',
	},
	[100000390] = {
		data = 'ccbResources/ani/cw_tumaoqiu.sprite',
		element_index = '宠物',
		element_name = '小月兔',
		id = 100000390,
		img = 'ccbResources/ani/cw_tumaoqiu.png',
	},
	[100000391] = {
		data = 'ccbResources/ani/cw_xianlu.sprite',
		element_index = '宠物',
		element_name = '小仙鹿',
		id = 100000391,
		img = 'ccbResources/ani/cw_xianlu.png',
	},
	[100000392] = {
		data = 'ccbResources/ani/cw_xiaohuanxiong.sprite',
		element_index = '宠物',
		element_name = '小浣熊',
		id = 100000392,
		img = 'ccbResources/ani/cw_xiaohuanxiong.png',
	},
	[100000393] = {
		data = 'ccbResources/ani/chdt_lianqiangpozhen.sprite',
		element_index = '称号',
		element_name = '连枪破阵',
		id = 100000393,
		img = 'ccbResources/ani/chdt_lianqiangpozhen.png',
	},
	[100000394] = {
		data = 'ccbResources/ani/chdt_luoshuinvshen.sprite',
		element_index = '称号',
		element_name = '洛水女神',
		id = 100000394,
		img = 'ccbResources/ani/chdt_luoshuinvshen.png',
	},
	[100000395] = {
		data = 'ccbResources/ani/chdt_yafuzhifeng.sprite',
		element_index = '称号',
		element_name = '亚夫之风',
		id = 100000395,
		img = 'ccbResources/ani/chdt_yafuzhifeng.png',
	},
	[100000396] = {
		data = 'ccbResources/ani/chdt_zhaohuzailin.sprite',
		element_index = '称号',
		element_name = '召虎再临',
		id = 100000396,
		img = 'ccbResources/ani/chdt_zhaohuzailin.png',
	},
	[100000397] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器100级上',
		id = 100000397,
		img = 'ccbResources/ani/wuqi_zy_lv13.png',
	},
	[100000398] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器120级上',
		id = 100000398,
		img = 'ccbResources/ani/wuqi_zy_lv14.png',
	},
	[100000399] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵8级上',
		id = 100000399,
		img = 'ccbResources/ani/wuqi_zy_lv16.png',
	},
	[100000400] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵9级上',
		id = 100000400,
		img = 'ccbResources/ani/wuqi_zy_lv15.png',
	},
	[100000401] = {
		data = 'ccbResources/ani/wuqi_zy_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵10级上',
		id = 100000401,
		img = 'ccbResources/ani/wuqi_zy_lv17.png',
	},
	[100000402] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器100级下',
		id = 100000402,
		img = 'ccbResources/ani/wuqi_zy_lv13.png',
	},
	[100000403] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云普通武器120级下',
		id = 100000403,
		img = 'ccbResources/ani/wuqi_zy_lv14.png',
	},
	[100000404] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵8级下',
		id = 100000404,
		img = 'ccbResources/ani/wuqi_zy_lv16.png',
	},
	[100000405] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵9级下',
		id = 100000405,
		img = 'ccbResources/ani/wuqi_zy_lv15.png',
	},
	[100000406] = {
		data = 'ccbResources/ani/wuqi_zy_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角赵云神兵10级下',
		id = 100000406,
		img = 'ccbResources/ani/wuqi_zy_lv17.png',
	},
	[100000407] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器100级上',
		id = 100000407,
		img = 'ccbResources/ani/wuqi_zg_lv13.png',
	},
	[100000408] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器120级上',
		id = 100000408,
		img = 'ccbResources/ani/wuqi_zg_lv14.png',
	},
	[100000409] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵8级上',
		id = 100000409,
		img = 'ccbResources/ani/wuqi_zg_lv16.png',
	},
	[100000410] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵9级上',
		id = 100000410,
		img = 'ccbResources/ani/wuqi_zg_lv15.png',
	},
	[100000411] = {
		data = 'ccbResources/ani/wuqi_zg_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵10级上',
		id = 100000411,
		img = 'ccbResources/ani/wuqi_zg_lv17.png',
	},
	[100000412] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器100级下',
		id = 100000412,
		img = 'ccbResources/ani/wuqi_zg_lv13.png',
	},
	[100000413] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛普通武器120级下',
		id = 100000413,
		img = 'ccbResources/ani/wuqi_zg_lv14.png',
	},
	[100000414] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵8级下',
		id = 100000414,
		img = 'ccbResources/ani/wuqi_zg_lv16.png',
	},
	[100000415] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵9级下',
		id = 100000415,
		img = 'ccbResources/ani/wuqi_zg_lv15.png',
	},
	[100000416] = {
		data = 'ccbResources/ani/wuqi_zg_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角诸葛神兵10级下',
		id = 100000416,
		img = 'ccbResources/ani/wuqi_zg_lv17.png',
	},
	[100000417] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器100级上',
		id = 100000417,
		img = 'ccbResources/ani/wuqi_dc_lv13.png',
	},
	[100000418] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器120级上',
		id = 100000418,
		img = 'ccbResources/ani/wuqi_dc_lv14.png',
	},
	[100000419] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵8级上',
		id = 100000419,
		img = 'ccbResources/ani/wuqi_dc_lv16.png',
	},
	[100000420] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵9级上',
		id = 100000420,
		img = 'ccbResources/ani/wuqi_dc_lv15.png',
	},
	[100000421] = {
		data = 'ccbResources/ani/wuqi_dc_lv1shang.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵10级上',
		id = 100000421,
		img = 'ccbResources/ani/wuqi_dc_lv17.png',
	},
	[100000422] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器100级下',
		id = 100000422,
		img = 'ccbResources/ani/wuqi_dc_lv13.png',
	},
	[100000423] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉普通武器120级下',
		id = 100000423,
		img = 'ccbResources/ani/wuqi_dc_lv14.png',
	},
	[100000424] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵8级下',
		id = 100000424,
		img = 'ccbResources/ani/wuqi_dc_lv16.png',
	},
	[100000425] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵9级下',
		id = 100000425,
		img = 'ccbResources/ani/wuqi_dc_lv15.png',
	},
	[100000426] = {
		data = 'ccbResources/ani/wuqi_dc_lv1xia.sprite',
		element_index = '主角武器',
		element_name = '主角貂蝉神兵10级下',
		id = 100000426,
		img = 'ccbResources/ani/wuqi_dc_lv17.png',
	},
}
